import React from 'react';
import {render,screen,fireEvent,waitFor,cleanup} from '@testing-library/react';
import {afterEach,describe,it,expect,vi} from 'vitest';
import {DEFAULT_PREFERENCES,SURGISUITE_REFERENCE,referenceNavigationTarget,translate,type LanguageKey} from '@pepbits/erp-config';
import {LocalizationProvider} from '@pepbits/ops-ui';
import copy from '../surgisuite-copy.json';
import {ReferenceHostProvider,type ReferenceHost} from '@pepbits/reference-host';
import {ReferenceSurgiSuiteModule} from './module';
import {SurgiSuiteDataProvider,useSourceApi} from './lib/api';
import {useSourceFormat} from './lib/format';
import {useStaff,useInvalidateMasters} from './lib/masters';
import fixtures from './__fixtures__/api.json';
afterEach(cleanup);
const data=fixtures as Record<string,any>,caseId=data['/cases'][0].id;
function host(handler?:(path:string,init?:RequestInit)=>Promise<any>):ReferenceHost{return {scope:{tenantId:'synthetic',applicationId:'nexora',branchId:'hq',userId:'synthetic',roles:['enterprise-admin'],moduleId:'reference-surgisuite'},preferences:{...DEFAULT_PREFERENCES},navigate:vi.fn(),request:vi.fn(async (path,init)=>{if(handler)return handler(path,init);const key=path.replace(/^\/api/,'').split('?')[0];if(!(key in data))throw new Error('Unmapped test request: '+key);return structuredClone(data[key]);})};}
describe('SurgiSuite source pages in shared host',()=>{
 it.each(['en','ar','hi','ml'] as LanguageKey[])('renders the original case tabs using the canonical %s catalog without translating API identifiers',async language=>{const h=host();h.preferences={...h.preferences,language};const t=(key:string)=>translate(language,key);render(<LocalizationProvider value={{language,direction:language==='ar'?'rtl':'ltr',t,dateTime:String}}><ReferenceSurgiSuiteModule host={h} path={'/cases/'+caseId}/></LocalizationProvider>);const nav=await screen.findByRole('navigation',{name:'Case sections'});for(const source of ['Overview','Team & equipment','Diagnosis & CPT','Approvals & consent','Checklist & counts','Anesthesia record','Imaging, lab & blood','Materials & implants','Risk scores','Operative report','Charges & claim','Activity & audit']){const key=(copy as Record<string,string>)[source];expect(key,source).toBeTruthy();const label=t(key);expect(label,source).not.toBe(key);if(language!=='en')expect(label,source).not.toBe(source);expect([...nav.querySelectorAll('button')].some(button=>button.textContent?.startsWith(label)),source).toBe(true);}expect(h.request).toHaveBeenCalledWith('/api/cases/'+caseId,expect.any(Object));});
 it('resolves eight static destinations and the real case identifier',()=>{expect(SURGISUITE_REFERENCE.pages).toHaveLength(9);expect(referenceNavigationTarget('reference-surgisuite','/cases/472').pageId).toBe('reference-surgisuite-case');expect(referenceNavigationTarget('reference-surgisuite','/cases/472').recordId).toBe('/cases/472');});
 it.each([['/','Theatre board'],['/schedule','Schedule'],['/cases','Cases'],['/approvals','Approvals'],['/patients','Patients'],['/inventory','Inventory'],['/analytics','Analytics'],['/masters','Masters & coding']])('renders %s from server fixtures through the host',async(path,title)=>{const h=host();render(<ReferenceSurgiSuiteModule host={h} path={path}/>);await screen.findByRole('heading',{name:title});expect(h.request).toHaveBeenCalledWith('/api/auth/me',expect.any(Object));expect(screen.queryByText(/Reset demo/i)).toBeNull();});
 it('keeps every original case workspace tab and opens each without throwing',async()=>{render(<ReferenceSurgiSuiteModule host={host()} path={'/cases/'+caseId}/>);const nav=await screen.findByRole('navigation',{name:'Case sections'});const tabs=['Overview','Team & equipment','Diagnosis & CPT','Approvals & consent','Checklist & counts','Anesthesia record','Imaging, lab & blood','Materials & implants','Risk scores','Operative report','Charges & claim','Activity & audit'];for(const name of tabs){const b=[...nav.querySelectorAll('button')].find(x=>x.textContent?.startsWith(name));expect(b,name).toBeTruthy();fireEvent.click(b!);await waitFor(()=>expect(b?.getAttribute('aria-current')).toBe('page'));}expect(screen.queryAllByRole('alert')).toHaveLength(0);});
 it('opens and dismisses the original booking drawer through the shared dialog',async()=>{render(<ReferenceSurgiSuiteModule host={host()} path="/"/>);await screen.findByRole('heading',{name:'Theatre board'});fireEvent.click(screen.getByRole('button',{name:'Book case'}));const dialog=await screen.findByRole('dialog');expect(dialog.textContent).toContain('Book');fireEvent.keyDown(document,{key:'Escape'});await waitFor(()=>expect(screen.queryByRole('dialog')).toBeNull());});
 it('shows failed authentication and recovers without invented records',async()=>{let allow=false;const h=host(async p=>{if(p==='/api/auth/me'&&!allow)throw Object.assign(new Error('Synthetic role denied'),{status:403});return structuredClone(data[p.replace(/^\/api/,'').split('?')[0]]);});render(<ReferenceSurgiSuiteModule host={h} path="/"/>);expect((await screen.findByRole('alert')).textContent).toContain('Synthetic role denied');expect(screen.queryByRole('heading',{name:'Theatre board'})).toBeNull();allow=true;fireEvent.click(screen.getByRole('button',{name:'Retry'}));await screen.findByRole('heading',{name:'Theatre board'});});
 it('does not offer booking for a viewer',async()=>{const h=host(async p=>p==='/api/auth/me'?{...data['/auth/me'],role:'VIEWER'}:structuredClone(data[p.replace(/^\/api/,'').split('?')[0]]));render(<ReferenceSurgiSuiteModule host={h} path="/"/>);await screen.findByRole('heading',{name:'Theatre board'});expect(screen.queryByRole('button',{name:'Book case'})).toBeNull();});
 it('follows date/time preferences while retaining the source denomination',()=>{function Format(){const f=useSourceFormat();return <p>{f.date('2026-10-02')}|{f.time('2026-10-02T14:30:00')}|{f.money(42)}</p>;}const h=host();h.preferences={...h.preferences,dateFormat:'dmy',timeFormat:'12h',currencyCode:'AED',currencyDisplay:'code'};render(<ReferenceHostProvider host={h}><Format/></ReferenceHostProvider>);expect(screen.getByText(/02\/10\/2026/).textContent).toContain('2:30');expect(screen.getByText(/02\/10\/2026/).textContent).toContain('USD');expect(screen.queryByText(/AED/)).toBeNull();});
 it('reuses write identity after an ambiguous error',async()=>{let attempts=0;const keys:string[]=[];const h=host(async(p,i)=>{if(p==='/api/patients'){keys.push(new Headers(i?.headers).get('Idempotency-Key')!);if(!attempts++)throw Object.assign(new Error('Response lost'),{status:503});return {id:1000};}return data['/auth/me'];});function Write(){const api=useSourceApi();return <button onClick={()=>void api('/patients',{body:{name:'Synthetic'}}).catch(()=>{})}>Create</button>;}render(<ReferenceHostProvider host={h}><SurgiSuiteDataProvider><Write/></SurgiSuiteDataProvider></ReferenceHostProvider>);fireEvent.click(screen.getByText('Create'));await waitFor(()=>expect(keys).toHaveLength(1));fireEvent.click(screen.getByText('Create'));await waitFor(()=>expect(keys).toHaveLength(2));expect(keys[0]).toBe(keys[1]);});
 it('refreshes open master consumers after master changes',async()=>{let revision=1;const h=host(async p=>p==='/api/staff'?[{id:revision,name:'Synthetic '+revision}]:data['/auth/me']);function Consumer(){const staff=useStaff(),invalidate=useInvalidateMasters();return <><p>{staff[0]?.name}</p><button onClick={()=>{revision=2;invalidate('/staff');}}>Refresh master</button></>;}render(<ReferenceHostProvider host={h}><SurgiSuiteDataProvider><Consumer/></SurgiSuiteDataProvider></ReferenceHostProvider>);await screen.findByText('Synthetic 1');fireEvent.click(screen.getByText('Refresh master'));await screen.findByText('Synthetic 2');});
});
