import {test} from 'node:test';import assert from 'node:assert/strict';
import {diagnosticScope,diagnosticPolicy} from './diagnostics-policy.mjs';
import {matchDiagnosticRoute} from '../desktop-clients/packages/reference-diagnostics/src/routes.ts';
const user={id:'user',tenantId:'tenant-a',role:'operations-analyst'},scope={applicationId:'nexora',branchId:'branch-a'};
test('diagnostic persistence separates module, tenant, application and branch',()=>{const values=[diagnosticScope('lis1',user,scope),diagnosticScope('lis2',user,scope),diagnosticScope('lis1',{...user,tenantId:'tenant-b'},scope),diagnosticScope('lis1',user,{...scope,branchId:'branch-b'}),diagnosticScope('lis1',user,{...scope,applicationId:'other'})];assert.equal(new Set(values).size,5);assert.equal(diagnosticScope('lis1',{...user,id:'other-user'},scope),values[0]);assert.throws(()=>diagnosticScope('lis1',{},scope));});
test('source login and identity switching cannot bypass the authenticated host',()=>{for(const role of ['enterprise-admin','finance-manager','operations-analyst']){assert.equal(diagnosticPolicy({role},'POST','/api/auth/login'),403);assert.equal(diagnosticPolicy({role},'POST','/api/session'),403);}assert.equal(diagnosticPolicy(user,'GET','/api/session'),200);});
test('read-only and finance roles cannot perform clinical or master writes',()=>{assert.equal(diagnosticPolicy(user,'POST','/api/orders'),403);assert.equal(diagnosticPolicy({...user,role:'finance-manager'},'POST','/api/orders'),403);assert.equal(diagnosticPolicy({...user,role:'finance-manager'},'POST','/api/billing/1/payments'),200);assert.equal(diagnosticPolicy({...user,role:'enterprise-admin'},'POST','/api/orders'),200);});
test('malformed and escaping diagnostic paths are refused',()=>{for(const path of ['/api/%2e%2e/users','/api/%ZZ','/api/../users','/api/\\other','https://other/api/orders'])assert.equal(diagnosticPolicy(user,'GET',path),400);assert.equal(diagnosticPolicy(user,'TRACE','/api/orders'),405);});
test('source detail routes preserve identifiers and prefer static new-order route',()=>{const routes=[{path:'/'},{path:'/orders/[id]'},{path:'/orders/new'},{path:'/print/report/[orderId]'}];assert.deepEqual(matchDiagnosticRoute(routes,'/orders/29?tab=result')?.params,{id:'29'});assert.equal(matchDiagnosticRoute(routes,'/orders/new')?.route.path,'/orders/new');assert.deepEqual(matchDiagnosticRoute(routes,'/print/report/14')?.params,{orderId:'14'});for(const bad of ['/orders/%2fsecret','/orders/%ZZ','/orders/..','/unknown','//evil'])assert.equal(matchDiagnosticRoute(routes,bad),null);});
