import {test} from 'node:test';import {randomUUID} from 'node:crypto';import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {createReferenceQualityStore,qualityScope,qualityRequestAllowed} from './reference-quality-store.mjs';
const admin={id:'quality-admin-test',name:'Synthetic Quality Administrator',email:'test@quality.example',role:'enterprise-admin',tenantId:'synthetic-quality'};
const scope={applicationId:'nexora',branchId:'hq'};
test('Quality trust boundary rejects fabricated roles and unsafe scope/path',()=>{
 assert.throws(()=>qualityScope(admin,{...scope,branchId:'../hq'}));
 assert.notEqual(qualityScope(admin,scope),qualityScope(admin,{...scope,branchId:'other'}));
 assert.notEqual(qualityScope(admin,scope),qualityScope({...admin,tenantId:'other'},scope));
 assert.equal(qualityRequestAllowed({...admin,role:'admin'},{method:'POST',path:'/users'}),403);
 assert.equal(qualityRequestAllowed(admin,{method:'POST',path:'/auth/login'}),403);
 assert.equal(qualityRequestAllowed(admin,{method:'GET',path:'/%2e%2e/users'}),400);
 assert.equal(qualityRequestAllowed(admin,{method:'GET',path:'/auth/me'}),200);
});
test('Quality actual SQLite workflows, actor, permissions, retry, version, correction and durable isolation',{timeout:120000},async()=>{
 const dir=await mkdtemp(join(tmpdir(),'pepbits-quality-test-'));let store=createReferenceQualityStore({dataDir:dir});
 const call=(method,path,body,actor=admin,s=scope,headers={})=>store.handle(actor,s,{method,path,body,headers:{...(!['GET','HEAD'].includes(method)?{'idempotency-key':randomUUID()}:{}),...headers}});
 try{
  const me=await call('GET','/auth/me');assert.equal(me.status,200);assert.equal(me.body.user.name,admin.name);assert.equal(me.body.user.email,admin.email);
  assert.equal(me.body.user.role,'admin');assert.ok(me.body.permissions.includes('users.manage'));
  const meta=await call('GET','/meta');assert.equal(meta.body.facilities.length,5);assert.equal(meta.body.tatDefinitions.length,13);
  assert.equal((await call('GET','/indicators')).body.length,32);assert.equal((await call('GET','/report-templates')).body.length,8);
  const viewer={...admin,id:'quality-read-only',role:'quality-viewer'};
  assert.equal((await call('GET','/dashboard',undefined,viewer)).status,200);
  assert.equal((await call('GET','/users',undefined,viewer)).status,403);
  assert.equal((await call('GET','/audit',undefined,viewer)).status,403);
  assert.equal((await call('POST','/authorities',{},admin,scope,{'idempotency-key':undefined})).status,400);
  const authority={code:'QTEST',name:'Synthetic Test Authority',jurisdiction:'Test',channel:'api',programs:['Test']};
  assert.equal((await call('POST','/authorities',authority,viewer)).status,403);
  const key={'idempotency-key':'quality-create-0001'};
  const created=await call('POST','/authorities',authority,admin,scope,key);assert.equal(created.status,201);
  assert.deepEqual(await call('POST','/authorities',authority,admin,scope,key),created);
  assert.equal((await call('POST','/authorities',{...authority,name:'Changed'},admin,scope,key)).status,409);
  assert.equal((await call('PUT','/users/'+me.body.user.id,{role:'viewer'})).status,403);
  const audit=await call('GET','/audit');assert.ok(audit.body.rows.some(r=>r.action==='authority.created'&&r.user_name===admin.name));
  assert.equal((await call('GET','/audit/verify')).body.valid,true);
  const candidates=(await call('GET','/results?status=draft')).body.filter(r=>r.blocking===0&&r.numerator!==null);
  assert.ok(candidates.length);const r=candidates[0];
  const edit={numerator:r.numerator,denominator:r.denominator,reason:'Synthetic version acceptance',version:r.version};
  const saved=await call('PUT','/results/'+r.id,edit,admin,scope,{'idempotency-key':'quality-edit-0001'});assert.equal(saved.status,200);
  assert.equal((await call('PUT','/results/'+r.id,edit)).status,409);
  const submitted=await call('POST','/results/'+r.id+'/submit',{});assert.equal(submitted.status,200,JSON.stringify(submitted.body));
  assert.equal((await call('POST','/results/'+r.id+'/verify',{})).status,409);
  const verifier={...admin,id:'quality-verifier-test',role:'quality-verifier'};
  assert.equal((await call('POST','/results/'+r.id+'/verify',{},verifier)).status,200);
  assert.equal((await call('POST','/results/'+r.id+'/approve',{},verifier)).status,403);
  const approver={...admin,id:'quality-approver-test',role:'quality-approver'};
  assert.equal((await call('POST','/results/'+r.id+'/approve',{},approver)).status,200);
  assert.equal((await call('PUT','/results/'+r.id,{...edit,version:r.version+1})).status,409);
  const event={transaction_id:'Q-ACCEPTANCE',domain:'lab',facility_id:1,event_type:'order_placed',occurred_at:'2026-09-10T08:00:00Z',source_system:'synthetic',source_event_key:'Q-event-1',patient_ref:'Synthetic QA'};
  const e=await call('POST','/events/ingest',event);assert.equal(e.status,201,JSON.stringify(e.body));
  assert.equal((await call('POST','/events/ingest',event)).body.outcome,'duplicate');
  const correction=await call('POST','/events/ingest',{...event,source_event_key:'Q-event-2',occurred_at:'2026-09-10T08:05:00Z',supersedes_event_id:e.body.event_id});assert.equal(correction.status,201);
  assert.equal((await call('POST','/events/ingest',{...event,source_event_key:'Q-event-3',supersedes_event_id:e.body.event_id})).status,409);
  assert.equal((await call('POST','/events/ingest',{...event,facility_id:2,source_event_key:'Q-event-4'})).status,409);
  assert.equal((await call('GET','/dashboard?facility=Infinity')).status,400);
  assert.equal((await call('GET','/tat/analysis?definition=1&from=2026-09-01&to=2026-09-30')).status,200);
  assert.equal((await call('GET','/tat/analysis?definition=1&from=2026-02-30&to=2026-09-30')).status,400);
  assert.equal((await call('GET','/tat/analysis?definition=1&from=2026-10-01&to=2026-09-30')).status,400);
  assert.equal((await call('POST','/reports/preview',{from:'bad',config:{sections:[]}})).status,400);
  const report=await call('GET','/report-templates/1/render');assert.equal(report.status,200);assert.match(report.body.checksum,/^[a-f0-9]{64}$/);
  const csv=await call('GET','/report-templates/1/export.csv');assert.equal(csv.status,200);assert.ok(Buffer.isBuffer(csv.body));assert.match(csv.headers['Content-Type'],/csv/);
  const other=await call('GET','/authorities',undefined,admin,{...scope,branchId:'other'});assert.equal(other.status,200);assert.equal(other.body.some(a=>a.code==='QTEST'),false);
  const otherTenant=await call('GET','/authorities',undefined,{...admin,tenantId:'other-tenant'});assert.equal(otherTenant.body.some(a=>a.code==='QTEST'),false);
  await store.close();store=createReferenceQualityStore({dataDir:dir});
  assert.ok((await call('GET','/authorities')).body.some(a=>a.code==='QTEST'));
  assert.deepEqual(await call('POST','/authorities',authority,admin,scope,key),created);
  assert.equal((await call('GET','/audit/verify')).body.valid,true);
 }finally{await store.close();await rm(dir,{recursive:true,force:true});}
});
