import {test} from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createServer} from 'node:net';
test('Healthcare Suite HTTP preserves host access grants, identity, product, branch and read-only boundaries',async t=>{
 const socket=createServer();await new Promise(resolve=>socket.listen(0,'127.0.0.1',resolve));const port=socket.address().port;await new Promise(resolve=>socket.close(resolve));
 const dir=mkdtempSync(join(tmpdir(),'reference-healthcare-suite-http-'));
 const child=spawn(process.execPath,[new URL('./server.mjs',import.meta.url).pathname],{env:{...process.env,HOST:'127.0.0.1',PORT:String(port),NEXORA_DATA_DIR:dir,RECORD_DATA_DIR:dir,APPROVAL_DELAY_MS:'0'},stdio:['ignore','pipe','pipe']});
 let output='';child.stdout.on('data',chunk=>output+=chunk);child.stderr.on('data',chunk=>output+=chunk);
 t.after(async()=>{if(child.exitCode===null){child.kill();await new Promise(resolve=>child.once('exit',resolve));}rmSync(dir,{recursive:true,force:true});});
 const base=`http://127.0.0.1:${port}`;let ready=false;for(let i=0;i<100;i++){try{await fetch(base);ready=true;break;}catch{await new Promise(resolve=>setTimeout(resolve,50));}}assert.ok(ready,output);
 const login=async username=>{const response=await fetch(base+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password:username})});assert.equal(response.status,200);return(await response.json()).token;};
 const admin=await login('admin'),finance=await login('user1'),operations=await login('user2'),teacher=await login('school-teacher');
 const call=(path,token,opts={})=>fetch(base+'/reference-modules/healthcare-suite/api'+path,{method:opts.method??'GET',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`} : {}),...opts.headers},...(opts.body===undefined?{}:{body:JSON.stringify(opts.body)})});
 assert.equal((await call('/session',null)).status,401);
 assert.equal((await call('/session',teacher)).status,403);
 assert.equal((await call('/session',admin,{headers:{'X-Product-Id':'ledger'}})).status,403);
 assert.equal((await call('/session',finance,{headers:{'X-Reference-Branch':'hq'}})).status,403);
 assert.equal((await call('/session',admin,{headers:{'X-Reference-Branch':'wrong'}})).status,403);
 const session=await call('/session?role=Doctor&userId=U001',admin,{headers:{'X-Reference-Facility':'F002'}});assert.equal(session.status,200,await session.clone().text());const s=await session.json();assert.equal(s.user.id,'USR-00301');assert.equal(s.user.role,'enterprise-admin');assert.equal(s.defaultFacilityId,'F002');
 assert.equal((await call('/session',admin,{headers:{'X-Reference-Facility':'other-branch'}})).status,403);
 assert.equal((await call('/dashboard',finance)).status,200);
 assert.equal((await call('/patients',finance,{method:'POST',body:{firstName:'Blocked'}})).status,403);
 const body={firstName:'HTTP',lastName:'Fictional Patient',gender:'Male',phone:'+971 50 765 9999'},headers={'Idempotency-Key':'http-create-1'};
 const create=await call('/patients',admin,{method:'POST',body,headers});assert.equal(create.status,201,await create.clone().text());const p=await create.json();
 const replay=await call('/patients',admin,{method:'POST',body,headers});assert.equal(replay.status,201);assert.equal((await replay.json()).id,p.id);
 assert.equal((await call(`/patients/${p.id}`,admin,{headers:{'X-Reference-Branch':'dubai'}})).status,404);
 assert.equal((await call(`/patients/${p.id}`,operations)).status,404);
 const encounter=await call('/encounters',admin,{method:'POST',headers:{'X-Reference-Facility':'F002'},body:{patientId:p.id,encounterType:'Pharmacy',paymentClass:'Cash',createdBy:'U001'}});assert.equal(encounter.status,201,await encounter.clone().text());const enc=await encounter.json();assert.equal(enc.createdBy,'USR-00301');assert.equal(enc.facilityId,'F002');
 const error=await call('/patients',admin,{method:'POST',body:{}});assert.equal(error.status,400);assert.equal((await error.json()).fields.firstName,'This field is required');
 const malformed=await fetch(base+'/reference-modules/healthcare-suite/api/patients',{method:'POST',headers:{Authorization:`Bearer ${admin}`,'Content-Type':'application/json'},body:'{invalid'});assert.equal(malformed.status,400);
 await fetch(base+'/auth/logout',{method:'POST',headers:{Authorization:`Bearer ${admin}`}});assert.equal((await call('/session',admin)).status,401);
});
