import {test} from 'node:test';
import assert from 'node:assert/strict';
process.env.APPROVAL_DELAY_MS='0';
const {createReferenceHealthcareSuiteStore}=await import('./reference-healthcare-suite-store.mjs');
const actor={id:'REAL-ADMIN',tenantId:'tenant-one',branch:'hq',role:'enterprise-admin',name:'Authenticated Host Actor',email:'admin@example.test',initials:'HA'};
const scope={applicationId:'nexora',branchId:'hq',moduleId:'reference-healthcare-suite'};
function fixture(){const store=createReferenceHealthcareSuiteStore();const call=(method,path,body,opts={})=>store.handle(opts.user??actor,opts.scope??scope,{method,path:'/api'+path,body,query:opts.query??{},headers:opts.headers??{}});const ok=(method,path,body,opts)=>{const result=call(method,path,body,opts);assert.ok(result.status<300,JSON.stringify(result));return result.body;};return{store,call,ok};}
const patient={firstName:'Synthetic',lastName:'Patient',gender:'Female',phone:'+971 50 123 8888',dob:'1990-01-01'};
const cash=(f,patientId,type='Outpatient',headers={})=>f.ok('POST','/encounters',{patientId,encounterType:type,paymentClass:'Cash',departmentId:'D001',specialtyId:'S001',providerId:'P001'},{headers});
const insurance=f=>{const check=f.ok('POST','/eligibility/check',{patientId:'PT00001',policyId:'POL00001'});assert.equal(check.status,'Eligible');return f.ok('POST','/encounters',{patientId:'PT00001',encounterType:'Outpatient',paymentClass:'Insurance',policyId:'POL00001',eligibilityRef:check.reference,departmentId:'D001',specialtyId:'S001',providerId:'P001'});};

test('session retains authenticated host actor and branch-local selected facility',()=>{const f=fixture(),s=f.ok('GET','/session',null,{query:{role:'Doctor',userId:'U001'},headers:{'X-Reference-Facility':'F002'}});assert.deepEqual(s.user,((({id,name,role,email,initials})=>({id,name,role,email,initials}))(actor)));assert.equal(s.defaultFacilityId,'F002');assert.equal(s.facilities.length,2);assert.equal(f.call('GET','/session',null,{headers:{'X-Reference-Facility':'foreign'}}).status,403);assert.equal(f.ok('GET','/health').ok,true);});

test('store enforces actor, product, role, module, branch and read-only writes',()=>{const f=fixture();for(const[user,s,status]of[[null,scope,401],[{...actor,role:'school-admin'},scope,403],[actor,{...scope,applicationId:'ledger'},403],[actor,{...scope,branchId:'other'},403],[actor,{...scope,moduleId:'reference-erp1'},403],[{...actor,role:'finance-manager',branch:'dubai'},scope,403]])assert.equal(f.store.handle(user,s,{method:'GET',path:'/api/dashboard'}).status,status);const readOnly={...actor,role:'finance-manager'};assert.equal(f.call('GET','/patients',null,{user:readOnly}).status,200);for(const method of ['POST','PUT','PATCH','DELETE'])assert.equal(f.call(method,'/patients',patient,{user:readOnly}).status,403);});

test('master CRUD and lookup contracts work for every original entity, preserving numeric form strings',()=>{const f=fixture();for(const entity of ['facilities','departments','specialties','providers','payers','tpas','insurance-plans','networks','items','services','price-lists','resources','resource-schedules','resource-blocks']){const list=f.ok('GET',`/masters/${entity}`);assert.ok(list.data.length,entity);const source=f.ok('GET',`/masters/${entity}/${list.data[0].id}`),body={...source};delete body.id;if(body.code)body.code+='-TEST';if(body.licenseNo)body.licenseNo+='-TEST';if(body.basePrice!==undefined)body.basePrice='25.50';const created=f.ok('POST',`/masters/${entity}`,body);assert.notEqual(created.id,source.id);if(body.basePrice!==undefined)assert.equal(created.basePrice,25.5);const updated=f.ok('PUT',`/masters/${entity}/${created.id}`,{...body,...(body.name?{name:'Updated '+body.name}:{reason:'Updated reason'})});assert.equal(updated.id,created.id);assert.equal(f.ok('PATCH',`/masters/${entity}/${created.id}/status`,{status:'Inactive'}).status,'Inactive');assert.ok(!f.ok('GET',`/lookups/${entity}`).some(row=>row.value===created.id));assert.ok(f.ok('GET',`/lookups/${entity}`,null,{query:{includeInactive:'true'}}).some(row=>row.value===created.id));}});

test('patient CRUD, duplicate fields and policy ownership are preserved',()=>{const f=fixture();assert.equal(f.call('POST','/patients',{}).body.fields.firstName,'This field is required');const p=f.ok('POST','/patients',patient);assert.match(p.mrn,/^MRN\d+/);assert.equal(f.ok('PUT',`/patients/${p.id}`,{...patient,email:'test@example.test'}).email,'test@example.test');const search=f.ok('GET','/patients',null,{query:{search:p.mrn}});assert.equal(search.total,1);assert.equal(f.call('PUT',`/patients/${p.id}`,{policies:[{...f.ok('GET','/patients/PT00001').policies[0]}]}).status,400);const original=f.ok('GET','/patients/PT00001');assert.equal(original.policies[0].memberId,'GSI-10045812');assert.equal(f.call('POST','/patients',{...patient,policies:'unsupported'}).status,400);});

test('slots, guest booking, blocked slots, reschedule, cancellation and repeated registration',()=>{const f=fixture(),day=new Date(Date.now()+86400000).toISOString().slice(0,10);const board=f.ok('GET','/scheduling/slots',null,{query:{date:day}}),resource=board.resources.find(row=>row.id==='R001'),slots=resource.slots.filter(slot=>slot.status==='free');assert.ok(slots.length>=2);const a=f.ok('POST','/appointments',{resourceId:'R001',date:day,startTime:slots[0].start,guestName:'Guest Person',guestPhone:'+971 50 333 4444',guestGender:'Male'});assert.equal(a.patientType,'Unregistered');assert.equal(f.call('POST','/appointments',{resourceId:'R001',date:day,startTime:slots[0].start,patientId:'PT00001'}).status,400);const reg=f.ok('POST',`/appointments/${a.id}/register`,{});assert.equal(f.ok('POST',`/appointments/${a.id}/register`,{}).patient.id,reg.patient.id);assert.equal(f.ok('PATCH',`/appointments/${a.id}/status`,{status:'Confirmed'}).status,'Confirmed');assert.equal(f.ok('PUT',`/appointments/${a.id}/reschedule`,{startTime:slots[1].start}).startTime,slots[1].start);assert.equal(f.call('PATCH',`/appointments/${a.id}/status`,{status:'Cancelled'}).body.fields.reason,'Give a reason for cancelling');assert.equal(f.ok('PATCH',`/appointments/${a.id}/status`,{status:'Cancelled',reason:'Demo cancellation'}).status,'Cancelled');const cancelled=f.ok('GET',`/appointments/${a.id}`);assert.deepEqual(f.ok('PATCH',`/appointments/${a.id}/status`,{status:'Cancelled',reason:'Retry'}),cancelled);assert.ok(!cancelled.notes.includes('Retry'));});

test('eligibility: ineligible member, expired policy, manual payer and insured visit requirements',()=>{const f=fixture();for(const[id,patientId,status]of[['POL00006','PT00006','Ineligible'],['POL00008','PT00008','Ineligible'],['POL00005','PT00005','Manual']])assert.equal(f.ok('POST','/eligibility/check',{policyId:id,patientId}).status,status);assert.equal(f.call('POST','/eligibility/check',{policyId:'POL00001',patientId:'PT00002'}).status,400);const missing=f.call('POST','/encounters',{patientId:'PT00001',encounterType:'Outpatient',paymentClass:'Insurance',policyId:'POL00001',departmentId:'D001',providerId:'P001'});assert.match(missing.body.fields.eligibility,/Check eligibility/);const enc=insurance(f);assert.equal(enc.createdBy,actor.id);assert.equal(enc.facilityId,'F001');assert.equal(enc.orders[0].status,'Signed');assert.equal(enc.orders[0].code,'SRV-CON-GP');});

test('full insured ordering: prior approval, eRx, billing holds, split hospital/pharmacy invoices and co-pay cap',()=>{const f=fixture(),enc=insurance(f);const mri=f.ok('POST',`/encounters/${enc.id}/orders`,{code:'SRV-RAD-MRIKN',qty:1});assert.equal(mri.priorAuthRequired,true);const catalog=f.ok('GET','/catalog/search',null,{query:{q:'Humira',policyId:'POL00001'}});assert.equal(catalog.length,1);const drug=f.ok('POST',`/encounters/${enc.id}/orders`,{code:catalog[0].code,qty:1,dosage:'1 pen',frequency:'Every two weeks'});assert.equal(drug.erxRequired,true);assert.equal(f.ok('POST',`/encounters/${enc.id}/orders/sign`,{orderIds:[mri.id,drug.id]}).signed,2);assert.deepEqual(f.ok('POST',`/encounters/${enc.id}/orders/sign`,{orderIds:[mri.id,drug.id]}),{signed:0});assert.equal(f.ok('GET',`/billing/preview/${enc.id}`,null,{query:{category:'Hospital'}}).blocked.length,1);assert.equal(f.ok('GET',`/billing/preview/${enc.id}`,null,{query:{category:'Pharmacy'}}).blocked.length,1);const pa=f.ok('POST',`/encounters/${enc.id}/approvals`,{channel:'PriorAuth',orderIds:[mri.id],diagnosis:'M23.2',justification:'Demo diagnosis'});const erx=f.ok('POST',`/encounters/${enc.id}/approvals`,{channel:'eRx',orderIds:[drug.id],diagnosis:'M06.9'});const approvals=f.ok('GET','/approvals');assert.equal(approvals.data.find(a=>a.id===pa.id).status,'Approved');assert.equal(approvals.data.find(a=>a.id===erx.id).status,'Approved');const hp=f.ok('GET',`/billing/preview/${enc.id}`,null,{query:{category:'Hospital'}});assert.equal(hp.blocked.length,0);assert.ok(hp.adjustments.some(a=>a.label.includes('capped')));const hospital=f.ok('POST','/billing/invoices',{encounterId:enc.id,category:'Hospital',payments:[{mode:'Cash',amount:10},{mode:'Card',amount:hp.totals.patientShare-10,reference:'SYNTH-123'}]});assert.equal(hospital.createdBy,actor.id);assert.equal(hospital.status,'Paid');const pharmacy=f.ok('POST','/billing/invoices',{encounterId:enc.id,category:'Pharmacy',payments:[]});assert.equal(hospital.copay+pharmacy.copay,50);assert.equal(hospital.net,hospital.patientShare+hospital.payerShare);assert.equal(pharmacy.net,pharmacy.patientShare+pharmacy.payerShare);assert.equal(f.ok('GET','/billing/invoices').total,2);assert.equal(f.ok('GET','/billing/pending',null,{query:{category:'Hospital'}}).total,0);assert.equal(f.ok('GET','/dashboard').revenue.collected,hospital.paid);});

test('rejected prior approval assigns patient share after settlement',()=>{const f=fixture(),enc=insurance(f),line=f.ok('POST',`/encounters/${enc.id}/orders`,{code:'SRV-RAD-MRIKN',qty:1});f.ok('POST',`/encounters/${enc.id}/orders/sign`,{orderIds:[line.id]});f.ok('POST',`/encounters/${enc.id}/approvals`,{channel:'PriorAuth',orderIds:[line.id],diagnosis:'Z00.0',justification:'Demo routine exam'});const pv=f.ok('GET',`/billing/preview/${enc.id}`,null,{query:{category:'Hospital'}}),rejected=pv.lines.find(l=>l.id===line.id);assert.equal(rejected.priorAuthStatus,'Rejected');assert.equal(rejected.patientShare,rejected.net);assert.equal(rejected.payerShare,0);});

test('payments, cancellation and invoice replay prevent repeat financial/stock effects',()=>{const f=fixture(),p=f.ok('POST','/patients',patient),enc=cash(f,p.id);const quote=f.ok('GET','/catalog/search',null,{query:{kind:'item',q:'Gloves'}})[0]??f.ok('GET','/catalog/search',null,{query:{kind:'item'}}).find(q=>!q.erxRequired&&q.category!=='Drug');assert.ok(quote);const line=f.ok('POST',`/encounters/${enc.id}/orders`,{code:quote.code,qty:1});f.ok('POST',`/encounters/${enc.id}/orders/sign`,{orderIds:[line.id]});const headers={'Idempotency-Key':'invoice-operation-1'},body={encounterId:enc.id,category:'Hospital',payments:[]},inv=f.ok('POST','/billing/invoices',body,{headers});assert.deepEqual(f.ok('POST','/billing/invoices',body,{headers}),inv);assert.equal(f.call('POST','/billing/invoices',{...body,payments:[{mode:'Cash',amount:1}]},{headers}).status,409);const payHeaders={'Idempotency-Key':'payment-operation-1'},pay={mode:'Cash',amount:10},paid=f.ok('POST',`/billing/invoices/${inv.id}/payments`,pay,{headers:payHeaders});assert.equal(f.ok('POST',`/billing/invoices/${inv.id}/payments`,pay,{headers:payHeaders}).paid,10);assert.equal(paid.balance,inv.balance-10);assert.equal(f.call('POST',`/billing/invoices/${inv.id}/payments`,{mode:'Card',amount:1}).status,400);const stockAfter=f.ok('GET','/pricing/quote',null,{query:{code:quote.code}}).stockQty;const cancel=f.ok('POST',`/billing/invoices/${inv.id}/cancel`,{reason:'Demo correction'});assert.equal(cancel.status,'Cancelled');f.ok('POST',`/billing/invoices/${inv.id}/cancel`,{reason:'Retry'});assert.equal(f.ok('GET','/pricing/quote',null,{query:{code:quote.code}}).stockQty,stockAfter+1);assert.equal(f.call('POST',`/billing/invoices/${inv.id}/payments`,pay).status,400);});

test('contract editing is atomic and blank override uses discounted default with flags',()=>{const f=fixture(),grid=f.ok('GET','/contracts/PL-GSI/lines'),line=grid.rows.find(row=>row.code==='SRV-CON-GP');assert.ok(line);assert.equal(f.call('PUT','/contracts/PL-GSI/lines',{lines:[{code:line.code,price:1,covered:true,priorAuth:false},{code:'UNKNOWN',price:1,covered:true,priorAuth:false}]}).status,404);assert.equal(f.ok('GET','/contracts/PL-GSI/lines').rows.find(row=>row.code===line.code).price,line.price);f.ok('PUT','/contracts/PL-GSI/lines',{lines:[{code:line.code,price:null,covered:false,priorAuth:true}]});const updated=f.ok('GET','/contracts/PL-GSI/lines').rows.find(row=>row.code===line.code);assert.equal(updated.price,line.defaultPrice);assert.equal(updated.covered,false);assert.equal(f.call('PUT','/contracts/PL-GSI/lines',{lines:[{code:line.code,price:'bad',covered:true,priorAuth:false}]}).status,400);});

test('partition identities isolate tenant, product and branch while sharing same branch data among actors',()=>{const f=fixture(),p=f.ok('POST','/patients',patient);assert.equal(f.ok('GET',`/patients/${p.id}`,null,{user:{...actor,id:'OTHER-ACTOR'}}).id,p.id);for(const opts of [{scope:{...scope,branchId:'dubai'}},{user:{...actor,tenantId:'tenant-two'}}])assert.equal(f.call('GET',`/patients/${p.id}`,null,opts).status,404);assert.equal(f.call('GET','/session',null,{scope:{...scope,applicationId:'ledger'}}).status,403);});

test('unknown/unsupported shapes fail before mutation and preserve field errors',()=>{const f=fixture();for(const[method,path,body]of[['POST','/patients',[]],['POST','/patients',{...patient,gender:[]}],['POST','/appointments',{guestName:{bad:1}}],['PUT','/contracts/PL-CASH/lines',{lines:{}}],['POST','/encounters',{encounterType:'unsupported'}],['POST','/encounters/EN000001/orders',{code:'SRV-CON-GP',qty:0}],['POST','/encounters/EN000001/orders/sign',{orderIds:'bad'}],['POST','/billing/invoices',{category:'wrong'}],['POST','/billing/invoices',{category:'Hospital',payments:[{mode:'Cash',amount:'bad'}]}]]){const result=f.call(method,path,body);assert.equal(result.status,400,JSON.stringify(result));assert.ok(result.body.fields);}assert.equal(f.call('GET','/missing').status,404);assert.equal(f.call('HEAD','/session').status,405);assert.equal(f.call('GET','/%').status,400);});

test('aggregate repeated item stock cannot be oversold and failed invoice leaves every line unchanged',()=>{const f=fixture(),p=f.ok('POST','/patients',patient),enc=cash(f,p.id),quote=f.ok('GET','/catalog/search',null,{query:{kind:'item'}}).find(q=>q.category!=='Drug'&&q.stockQty>0);const a=f.ok('POST',`/encounters/${enc.id}/orders`,{code:quote.code,qty:quote.stockQty}),b=f.ok('POST',`/encounters/${enc.id}/orders`,{code:quote.code,qty:quote.stockQty});f.ok('POST',`/encounters/${enc.id}/orders/sign`,{orderIds:[a.id,b.id]});const failed=f.call('POST','/billing/invoices',{encounterId:enc.id,category:'Hospital',payments:[]});assert.equal(failed.status,400);assert.equal(failed.body.fields.stock,'Combined quantities exceed available stock');assert.equal(f.ok('GET','/pricing/quote',null,{query:{code:quote.code}}).stockQty,quote.stockQty);assert.equal(f.ok('GET','/billing/invoices').total,0);assert.ok(f.ok('GET',`/encounters/${enc.id}`).orders.every(order=>order.status==='Signed'));});

test('dosing edits, approval in-flight protection and quantity changes invalidate approval of old quantities',()=>{const f=fixture(),enc=insurance(f),quote=f.ok('GET','/catalog/search',null,{query:{q:'Humira',policyId:'POL00001'}})[0];const order=f.ok('POST',`/encounters/${enc.id}/orders`,{code:quote.code,qty:1});assert.equal(f.call('POST',`/encounters/${enc.id}/orders/sign`,{orderIds:[order.id]}).status,400);f.ok('PUT',`/orders/${order.id}`,{dosage:'1 pen',frequency:'Every two weeks'});f.ok('POST',`/encounters/${enc.id}/approvals`,{channel:'eRx',orderIds:[order.id],diagnosis:'M06.9'});assert.equal(f.call('PUT',`/orders/${order.id}`,{qty:2}).status,400);const approved=f.ok('GET',`/encounters/${enc.id}`).orders.find(line=>line.id===order.id);assert.equal(approved.erxStatus,'Approved');const changed=f.ok('PUT',`/orders/${order.id}`,{qty:2});assert.equal(changed.qty,2);assert.equal(changed.erxStatus,'Required');assert.equal(changed.erxId,'');assert.equal(changed.approvalId,'');f.ok('DELETE',`/orders/${order.id}`);assert.ok(!f.ok('GET',`/encounters/${enc.id}`).orders.some(line=>line.id===order.id));});

test('booking checks resource blocks and encounter check-in links appointment while keeping selected facility',()=>{const f=fixture(),day=new Date(Date.now()+86400000).toISOString().slice(0,10);f.ok('POST','/masters/resource-blocks',{resourceId:'R001',date:day,startTime:'08:00',endTime:'08:15',reason:'Fictional equipment check'});const blocked=f.call('POST','/appointments',{resourceId:'R001',date:day,startTime:'08:00',patientId:'PT00001'});assert.equal(blocked.status,400);assert.match(blocked.body.message,/blocked/);const free=f.ok('GET','/scheduling/slots',null,{query:{date:day,resourceIds:'R001'}}).resources[0].slots.find(slot=>slot.status==='free');const appt=f.ok('POST','/appointments',{resourceId:'R001',date:day,startTime:free.start,patientId:'PT00001'});const enc=f.ok('POST','/encounters',{patientId:'PT00001',appointmentId:appt.id,encounterType:'Walk-in',paymentClass:'Cash',departmentId:'D001',specialtyId:'S001',providerId:'P001'},{headers:{'X-Reference-Facility':'F002'}});assert.equal(enc.facilityId,'F002');assert.equal(enc.appointment.id,appt.id);assert.equal(f.ok('GET',`/appointments/${appt.id}`).status,'Arrived');f.ok('PATCH',`/encounters/${enc.id}/status`,{status:'Completed'});assert.equal(f.ok('GET',`/appointments/${appt.id}`).status,'Completed');f.ok('PATCH',`/encounters/${enc.id}/status`,{status:'In Consultation'});assert.equal(f.ok('GET',`/appointments/${appt.id}`).status,'In Consultation');assert.equal(f.call('POST','/encounters',{patientId:'PT00002',encounterType:'Pharmacy',paymentClass:'Cash',facilityId:'F001'},{headers:{'X-Reference-Facility':'F002'}}).body.fields.facilityId,'Facility differs from the selected facility');});


test('invoice creation treats zero as an unfilled payment row while later collection requires positive payment',()=>{const f=fixture(),p=f.ok('POST','/patients',patient),enc=cash(f,p.id),inv=f.ok('POST','/billing/invoices',{encounterId:enc.id,category:'Hospital',payments:[{mode:'Cash',amount:0}]});assert.equal(inv.status,'Unpaid');assert.equal(inv.paid,0);assert.deepEqual(inv.payments,[]);assert.equal(inv.balance,inv.patientShare);const result=f.call('POST',`/billing/invoices/${inv.id}/payments`,{mode:'Cash',amount:0});assert.equal(result.status,400);assert.equal(result.body.fields.amount,'Enter an amount greater than zero');assert.deepEqual(f.ok('GET',`/billing/invoices/${inv.id}`).payments,[]);});
