import {test} from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtempSync,rmSync,readFileSync,writeFileSync,cpSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createServer} from 'node:net';

test('Teleconsult HTTP sessions, role grants, shared views and adopted branch policy',async t=>{
 const socket=createServer();await new Promise(r=>socket.listen(0,'127.0.0.1',r));const port=socket.address().port;await new Promise(r=>socket.close(r));
 const dir=mkdtempSync(join(tmpdir(),'teleconsult-http-')),config=join(dir,'config');cpSync(new URL('./config',import.meta.url),config,{recursive:true});
 const policyPath=join(config,'teleconsult/nexora.json'),policy=JSON.parse(readFileSync(policyPath,'utf8'));policy.defaults.access.allowPatientBooking=true;policy.tenants['NEX-AE-001'].branches.hq={modes:['audio']};writeFileSync(policyPath,JSON.stringify(policy));
 let log='';const child=spawn(process.execPath,[new URL('./server.mjs',import.meta.url).pathname],{env:{...process.env,HOST:'127.0.0.1',PORT:String(port),NEXORA_DATA_DIR:join(dir,'data'),RECORD_DATA_DIR:join(dir,'records'),NEXORA_CONFIG_DIR:config},stdio:['ignore','pipe','pipe']});child.stdout.on('data',b=>{log+=b});child.stderr.on('data',b=>{log+=b});
 t.after(async()=>{if(child.exitCode===null){child.kill();await new Promise(r=>child.once('exit',r));}rmSync(dir,{recursive:true,force:true});});
 const base=`http://127.0.0.1:${port}`;let ready=false;for(let i=0;i<120;i++){if(child.exitCode!==null)throw Error(log);try{const r=await fetch(base+'/health');if(r.ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,50));}assert.ok(ready,log);
 const login=async username=>{const r=await fetch(base+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password:username})});assert.equal(r.status,200);return (await r.json()).token;};
 const [admin,nurse,doctor,patient,viewer]=await Promise.all(['admin','teleconsult-nurse','teleconsult-doctor','teleconsult-patient','user2'].map(login));
 const api=async(token,variant,path,method='GET',body,headers={})=>{const r=await fetch(base+`/reference-modules/teleconsult-${variant}/api`+path,{method,headers:{Authorization:`Bearer ${token}`,'X-Product-Id':'nexora','X-Reference-Branch':'hq','Content-Type':'application/json',...(body!==undefined?{'Idempotency-Key':crypto.randomUUID()}:{}),...headers},...(body!==undefined?{body:JSON.stringify(body)}:{})});return {status:r.status,body:await r.json()};};
 assert.equal((await api('invalid','provider','/session')).status,401);
 assert.equal((await api(viewer,'provider','/session')).status,403);
 assert.equal((await api(nurse,'provider','/session?role=doctor')).status,403);
 const ns=await api(nurse,'provider','/session');assert.equal(ns.status,200);assert.deepEqual(ns.body.roles,['nurse']);assert.equal(ns.body.user.id,'n1');assert.deepEqual(ns.body.settings.modes,['audio']);
 const ds=await api(doctor,'provider','/session');assert.equal(ds.status,200);assert.deepEqual(ds.body.roles,['doctor']);
 assert.equal((await api(patient,'provider','/session')).status,403);
 const ps=await api(patient,'patient','/session');assert.equal(ps.status,200);assert.equal(ps.body.patient.id,'p8');assert.equal(ps.body.patients.length,1);assert.equal(ps.body.canRegister,false);
 assert.equal((await api(patient,'patient','/session?patientId=p1')).status,403);
 assert.equal((await api(patient,'patient','/patients/p1')).status,403);
 assert.equal((await api(patient,'patient','/patients','POST',{firstName:'Unauthorized'})).status,403);
 assert.equal((await api(patient,'patient','/session','GET',undefined,{'X-Reference-Branch':'dubai'})).status,403);
 const adminPatient=await api(admin,'patient','/session?patientId=p8');assert.equal(adminPatient.status,200);assert.equal(adminPatient.body.patient.id,'p8');
 const day=new Date(Date.now()+86400000).toISOString().slice(0,10),slots=await api(patient,'patient',`/slots?clinicianId=d1&date=${day}T12:00:00`);assert.equal(slots.status,200);const slot=slots.body.find(s=>s.available);assert.ok(slot);
 const body={patientId:'p8',clinicianId:'d1',start:slot.start,mode:'audio',reason:'HTTP synthetic acceptance',priority:'routine'},key=crypto.randomUUID();
 const booked=await api(patient,'patient','/appointments','POST',body,{'Idempotency-Key':key});assert.equal(booked.status,201,JSON.stringify(booked.body));
 const replay=await api(patient,'patient','/appointments','POST',body,{'Idempotency-Key':key});assert.deepEqual(replay.body,booked.body);
 assert.equal((await api(patient,'patient','/appointments','POST',{...body,patientId:'p1'})).status,403);
 const shared=await api(doctor,'provider','/appointments/'+booked.body.id);assert.equal(shared.status,200);assert.equal(shared.body.patient.id,'p8');
 const joined=await api(patient,'patient',`/appointments/${booked.body.id}/join`,'POST',{});assert.equal(joined.status,200);assert.equal(joined.body.status,'waiting');
 const triaged=await api(nurse,'provider',`/appointments/${booked.body.id}`,'PATCH',{status:'triage',triagedBy:'n1'});assert.equal(triaged.status,200);
 const denied=await api(nurse,'provider',`/appointments/${booked.body.id}`,'PATCH',{status:'in-call'});assert.equal(denied.status,403);
});
