import React from 'react';
import { fireEvent, render, screen } from '@testing-library/react';
import { describe, expect, it, vi } from 'vitest';
import { QuantityUnitField, type QuantityUnitFieldProps } from './quantity-unit-field';
const base:QuantityUnitFieldProps={label:'Supply amount',quantityLabel:'Requested quantity',unitLabel:'Pack unit',value:{quantity:'2.000',unit:'box'},options:[{value:'each',label:'Each'},{value:'box',label:'Box of 100'}],onChange:()=>{}};
describe('QuantityUnitField',()=>{
 it('provides a named group and independent control labels',()=>{render(<QuantityUnitField {...base} quantityHint="Entered stock amount" unitHint="Configured packaging"/>);expect(screen.getByRole('group',{name:'Supply amount'})).toBeInTheDocument();expect(screen.getByRole('textbox',{name:'Requested quantity'})).toHaveAccessibleDescription('Entered stock amount');expect(screen.getByRole('combobox',{name:'Pack unit'})).toHaveAccessibleDescription('Configured packaging');expect(screen.getByRole('textbox')).toHaveAttribute('inputmode','decimal');});
 it('preserves decimal text and does not parse incomplete or large entries',()=>{const changed=vi.fn();render(<QuantityUnitField {...base} onChange={changed}/>);for(const quantity of ['0.','0002.000000','999999999999999999999999','']){fireEvent.change(screen.getByRole('textbox'),{target:{value:quantity}});expect(changed).toHaveBeenLastCalledWith({quantity,unit:'box'});}expect(screen.getByRole('textbox')).toHaveValue('2.000');});
 it('unit selection retains quantity; the host controls the resulting pair',()=>{const changed=vi.fn();const {rerender}=render(<QuantityUnitField {...base} onChange={changed}/>);fireEvent.change(screen.getByRole('combobox'),{target:{value:'each'}});expect(changed).toHaveBeenCalledWith({quantity:'2.000',unit:'each'});rerender(<QuantityUnitField {...base} value={{quantity:'200',unit:'each'}}/>);expect(screen.getByRole('textbox')).toHaveValue('200');expect(screen.getByRole('combobox')).toHaveValue('each');});
 it('shows only the exact current host preview and suppresses stale pairs',()=>{const preview={forValue:base.value,content:'2 boxes = 200 each'};const {rerender}=render(<QuantityUnitField {...base} preview={preview}/>);expect(screen.getByRole('status')).toHaveTextContent('2 boxes = 200 each');rerender(<QuantityUnitField {...base} value={{quantity:'3',unit:'box'}} preview={preview}/>);expect(screen.queryByRole('status')).not.toBeInTheDocument();rerender(<QuantityUnitField {...base} value={{quantity:'2.000',unit:'each'}} preview={preview}/>);expect(screen.queryByRole('status')).not.toBeInTheDocument();});
 it.each(['disabled','readOnly','loading'] as const)('%s locks callbacks and unit changes without changing values',lock=>{const changed=vi.fn();render(<QuantityUnitField {...base} {...{[lock]:true}} onChange={changed} loadingLabel="Checking units" preview={{forValue:base.value,content:'Old preview'}}/>);const quantity=screen.getByRole('textbox'),unit=screen.getByRole('combobox');expect(unit).toBeDisabled();if(lock==='readOnly')expect(quantity).toHaveAttribute('readonly');else expect(quantity).toBeDisabled();fireEvent.change(quantity,{target:{value:'9'}});fireEvent.change(unit,{target:{value:'each'}});expect(changed).not.toHaveBeenCalled();if(lock==='loading'){expect(screen.getByRole('group')).toHaveAttribute('aria-busy','true');expect(screen.getByRole('status')).toHaveTextContent('Checking units');expect(screen.queryByText('Old preview')).not.toBeInTheDocument();}});
 it('links host validation to both controls and hides a successful preview',()=>{render(<QuantityUnitField {...base} error="Pack changed; review again" quantityHint="No rounding" preview={{forValue:base.value,content:'Stale conversion'}}/>);expect(screen.getByRole('alert')).toHaveTextContent('Pack changed; review again');expect(screen.getByRole('textbox')).toHaveAttribute('aria-invalid','true');expect(screen.getByRole('combobox')).toHaveAttribute('aria-invalid','true');expect(screen.getByRole('textbox')).toHaveAccessibleDescription('Pack changed; review again No rounding');expect(screen.queryByText('Stale conversion')).not.toBeInTheDocument();});
 it('renders supplied RTL labels and long unit names without changing identifiers',()=>{render(<div dir="rtl"><QuantityUnitField {...base} label="كمية الصنف" quantityLabel="الكمية" unitLabel="الوحدة" options={[{value:'box',label:'عبوة طويلة — صندوق يحتوي على مائة وحدة'}]}/></div>);expect(screen.getByRole('group',{name:'كمية الصنف'})).toBeInTheDocument();expect(screen.getByRole('textbox',{name:'الكمية'})).toHaveValue('2.000');expect(screen.getByRole('combobox',{name:'الوحدة'})).toHaveValue('box');});
});
