import React from 'react';
import {describe,it,expect,vi} from 'vitest';
import {render,screen,fireEvent,waitFor} from '@testing-library/react';
import {MasterTransferPanel,type MasterTransferPort} from './panel';
const port=():MasterTransferPort=>({preview:vi.fn().mockResolvedValue({valid:true,rows:[{code:'A'}],issues:[]}),commit:vi.fn().mockResolvedValue({imported:1}),exportPage:vi.fn().mockResolvedValue({columns:['code'],rows:[],nextAfter:null})});
async function upload(){const f=new File(['code\nA'],'items.csv',{type:'text/csv'});Object.defineProperty(f,'arrayBuffer',{value:async()=>new TextEncoder().encode('code\nA').buffer});fireEvent.change(screen.getByLabelText('CSV or Excel file'),{target:{files:[f]}});await screen.findByText('1 records loaded.');fireEvent.change(screen.getByLabelText('Change reason'),{target:{value:'Approved catalogue setup'}});}
describe('master transfer commands',()=>{
 it('requires server validation and invalidates it on changed reason',async()=>{const p=port();render(<MasterTransferPanel port={p} columns={['code']} name="items"/>);await upload();expect(screen.getByText('Import validated records')).toBeDisabled();fireEvent.click(screen.getByText('Validate file'));await screen.findByText(/Validation passed/);fireEvent.change(screen.getByLabelText('Change reason'),{target:{value:'Other reason'}});expect(screen.getByText('Import validated records')).toBeDisabled();fireEvent.click(screen.getByText('Validate file'));await screen.findByText(/Validation passed/);fireEvent.click(screen.getByText('Import validated records'));await screen.findByText(/Import committed/);expect(p.commit).toHaveBeenCalledTimes(1);});
 it('retains idempotency key when commit response fails',async()=>{const p=port();vi.mocked(p.commit).mockRejectedValueOnce(new Error('Network failed'));render(<MasterTransferPanel port={p} columns={['code']} name="items"/>);await upload();fireEvent.click(screen.getByText('Validate file'));await screen.findByText(/Validation passed/);fireEvent.click(screen.getByText('Import validated records'));await screen.findByText('Network failed');fireEvent.click(screen.getByText('Import validated records'));await waitFor(()=>expect(p.commit).toHaveBeenCalledTimes(2));expect(vi.mocked(p.commit).mock.calls[0][2]).toBe(vi.mocked(p.commit).mock.calls[1][2]);});
 it('does not enable commit for validation errors',async()=>{const p=port();vi.mocked(p.preview).mockResolvedValue({valid:false,rows:[],issues:[{row:2,field:'code',message:'Already exists'}]});render(<MasterTransferPanel port={p} columns={['code']} name="items"/>);await upload();fireEvent.click(screen.getByText('Validate file'));await screen.findByText('Row 2, code: Already exists');expect(screen.getByText('Import validated records')).toBeDisabled();});
});
