'use client';
import React,{useRef,useState} from 'react';
import {Button,Input,Select} from '@pepbits/ops-ui';
import {useLocalization} from '@pepbits/ops-ui';
import {exportMasterTransfer,readMasterTransfer,type MasterTransferData} from './format';
export interface MasterTransferPreview {valid:boolean;rows:Record<string,unknown>[];issues:Array<{row:number;field:string;message:string}>;}
export interface MasterTransferPort {
 preview(rows:Record<string,string>[],reason:string):Promise<MasterTransferPreview>;
 commit(rows:Record<string,string>[],reason:string,idempotencyKey:string):Promise<unknown>;
 exportPage(after:number):Promise<MasterTransferData&{nextAfter:number|null}>;
}
export interface MasterTransferPanelProps {port:MasterTransferPort;columns:string[];name:string;canImport?:boolean;canExport?:boolean;onImported?():void;mode?:'CREATE'|'UPSERT';}
/** No persistence or authority in the browser: the host supplies authenticated, tenant-scoped operations. */
export function MasterTransferPanel({port,columns,name,canImport=true,canExport=true,onImported,mode='CREATE'}:MasterTransferPanelProps){
 const {t}=useLocalization();
 const [data,setData]=useState<MasterTransferData>(),[review,setReview]=useState<MasterTransferPreview>(),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[format,setFormat]=useState<'csv'|'xlsx'>('csv');
 const pending=useRef<{body:string;key:string}|undefined>(undefined),lock=useRef(false);
 const run=async(action:()=>Promise<void>)=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');setMessage('');try{await action();}catch(e){setError(e instanceof Error?e.message:'Transfer failed.');}finally{lock.current=false;setBusy(false);}};
 const download=(records:MasterTransferData,suffix:string)=>{const bytes=exportMasterTransfer(records,format);const url=URL.createObjectURL(new Blob([bytes as BlobPart],{type:format==='csv'?'text/csv;charset=utf-8':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}));const a=document.createElement('a');a.href=url;a.download=name+'-'+suffix+'.'+format;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <section aria-label={t("Import and export masters")} className="card"><h2>{t("Import and export")}</h2><p>{t("Download a template, enter literal values, then validate before importing.")} {mode==='CREATE'?'Imports create new draft records; existing records are never overwritten.':'Existing codes are updated only with the exported __version. New codes create drafts. Download current records before editing.'} {t('Use reference codes, not database IDs. Maximum 500 records per file.')}</p><fieldset disabled={busy}><div className="actions"><label>{t("File format")}<Select value={format} onChange={e=>setFormat(e.target.value as 'csv'|'xlsx')} options={[{value:'csv',label:'CSV'},{value:'xlsx',label:'Excel XLSX'}]}/></label><Button type="button" disabled={!canExport} onClick={()=>download({columns,rows:[]},'template')}>{t("Download template")}</Button><Button type="button" disabled={!canExport} onClick={()=>void run(async()=>{let after=0;const all:MasterTransferData={columns:[],rows:[]};const seen=new Set<number>();for(;;){if(seen.has(after))throw new Error('Invalid export cursor.');seen.add(after);const page=await port.exportPage(after);if(all.columns.length&&JSON.stringify(all.columns)!==JSON.stringify(page.columns))throw new Error('Columns changed during export. Please retry.');all.columns=page.columns;all.rows.push(...page.rows);if(all.rows.length>10000)throw new Error('Export exceeds 10,000 rows. Narrow the selection.');if(page.nextAfter===null)break;after=page.nextAfter;}download(all,'records');setMessage(all.rows.length+' records exported.');})}>{t("Export records")}</Button></div>
 {canImport&&<><label>{t("CSV or Excel file")}<Input type="file" accept=".csv,.xlsx" onChange={e=>{const file=e.target.files?.[0];setReview(undefined);setData(undefined);pending.current=undefined;if(file)void run(async()=>{if(file.size>2*1024*1024)throw new Error('Choose a file up to 2 MB.');const parsed=await readMasterTransfer(file.name,new Uint8Array(await file.arrayBuffer()));const unknown=parsed.columns.filter(c=>!columns.includes(c));if(unknown.length)throw new Error('Unknown columns: '+unknown.join(', '));setData(parsed);});}}/></label><label>{t('Change reason')}<Input value={reason} maxLength={500} onChange={e=>{setReason(e.target.value);setReview(undefined);pending.current=undefined;}}/></label><div className="actions"><Button type="button" disabled={!data||!reason.trim()} onClick={()=>void run(async()=>{setReview(await port.preview(data!.rows,reason));})}>{t("Validate file")}</Button><Button type="button" disabled={!data||!review?.valid||review.issues.length>0||!reason.trim()} onClick={()=>void run(async()=>{const body=JSON.stringify({rows:data!.rows,reason});if(pending.current?.body!==body)pending.current={body,key:crypto.randomUUID()};await port.commit(data!.rows,reason,pending.current.key);setMessage('Import committed. Refresh the records to review the changed records.');setReview(undefined);setData(undefined);pending.current=undefined;onImported?.();})}>{t("Import validated records")}</Button></div></>}
 </fieldset>{busy&&<p role="status">{t("Processing…")}</p>}{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{data&&<p>{data.rows.length} {t("records loaded.")}</p>}{review&&<div><p role="status">{review.valid?'Validation passed. The server will revalidate when importing.':'Correct the reported issues and upload the file again.'}</p><ul>{review.issues.slice(0,100).map((issue,i)=><li key={i}>{t('Row')} {issue.row}, {issue.field}: {issue.message}</li>)}</ul>{review.issues.length>100&&<p>{t("Showing the first 100 issues.")}</p>}</div>}</section>;
}
