"use client";
import { LocalizedText, useLocalization } from "@pepbits/ops-ui";
import { SourceButton, SourceInput } from "../../../shared/controls";
import { useEffect, useRef, useState } from "react";
import { Send, Sparkles } from "lucide-react";
import type { ChatMessage } from "../../../shared/types";
import { useConsult } from "./context";
import { useApi } from "../../lib/hooks";
import { useTeleconsultClient } from "../../lib/api";
import { useTeleconsultFormat } from "../../lib/format";
import { Button, DemoNotice, Segmented, cx, useToast } from "../ui";

const QUICK = [
  "I'll be with you in a moment.",
  "Could you point the camera at the area, please?",
  "Please take a reading with your BP cuff now.",
  "Your prescription has been sent to your pharmacy.",
];

export function CommsPanel({ onScribe, scribing }: { onScribe: () => void; scribing: boolean }) {
  const { t } = useLocalization();
  const { appt, user, enc, locked } = useConsult();
  const client = useTeleconsultClient();
  const { fmtTime } = useTeleconsultFormat();
  const toast = useToast();
  const [tab, setTab] = useState<"chat" | "transcript">("chat");
  const msgs = useApi<ChatMessage[]>(`/api/appointments/${appt.id}/messages`, { poll: 2500 });
  const [text, setText] = useState("");
  const listRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (enc.recording.active) setTab("transcript");
  }, [enc.recording.active]);

  useEffect(() => {
    const el = listRef.current;
    if (el) el.scrollTop = el.scrollHeight;
  }, [msgs.data?.length, enc.transcript.length, tab]);

  const send = async (t = text) => {
    if (!t.trim()) return;
    try {
      // Identical retries of the same message reuse one Idempotency-Key, so a replay cannot duplicate it.
      await client.post(`/api/appointments/${appt.id}/messages`, { from: "staff", author: user?.name ?? "Clinician", text: t });
      if (t === text) setText("");
      msgs.reload();
    } catch (e) {
      toast((e as Error).message, "error");
    }
  };

  return (
    <section className="flex min-h-[220px] flex-col rounded-lg border border-line bg-white shadow-panel">
      <header className="flex items-center gap-2 border-b border-line px-2.5 py-2">
        <Segmented size="sm" value={tab} onChange={setTab} options={[{ value: "chat", label: `${t("Chat")}${msgs.data?.length ? ` · ${msgs.data.length}` : ""}` }, { value: "transcript", label: `${t("Transcript")}${enc.transcript.length ? ` · ${enc.transcript.length}` : ""}` }]} />
        {tab === "transcript" && (
          <Button size="sm" variant="quiet" className="ml-auto" loading={scribing} disabled={locked} onClick={onScribe} icon={<Sparkles className="h-3.5 w-3.5 text-pulse-600" />}>
            
            <LocalizedText message={"Draft note"} />
          </Button>
        )}
      </header>
      <div ref={listRef} className="min-h-0 flex-1 overflow-y-auto px-3 py-2 scroll-thin">
        {tab === "chat" ? (
          <ul className="space-y-2">
            {msgs.data?.map((m) => (
              <li key={m.id} className={cx("flex", m.author === "System" ? "justify-center" : m.from === "staff" ? "justify-end" : "justify-start")}>
                {m.author === "System" ? (
                  <span className="text-2xs text-ink-400">{m.text} · {fmtTime(m.at)}</span>
                ) : (
                  <span className={cx("max-w-[85%] rounded-lg px-2.5 py-1.5 text-[13px]", m.from === "staff" ? "bg-pulse-500 text-white" : "bg-canvas text-ink")}>
                    {m.text}
                    <span className={cx("ml-2 text-2xs", m.from === "staff" ? "text-pulse-100" : "text-ink-400")}>{fmtTime(m.at)}</span>
                  </span>
                )}
              </li>
            ))}
            {!msgs.data?.length && <li className="py-6 text-center text-xs text-ink-400"><LocalizedText message={"Messages with the patient appear here and in their app."} /></li>}
          </ul>
        ) : (
          <ul className="space-y-1.5">
            {enc.transcript.map((l) => (
              <li key={l.id} className="text-[13px] leading-snug animate-rise">
                <span className={cx("mr-1.5 text-2xs font-semibold", l.speaker === "clinician" ? "text-pulse-600" : "text-[#7A4FA3]")}>{t(l.speaker === "clinician" ? "Clinician (simulated)" : "Patient (simulated)")}</span>
                <span className="text-ink">{l.text}</span>
              </li>
            ))}
            <li><DemoNotice><LocalizedText message={"Demo transcript: scripted lines generated by the API, not speech recognized from this call."} /></DemoNotice></li>
            {!enc.transcript.length && (
              <li className="py-6 text-center text-xs text-ink-400">
                {t(enc.recording.active ? "Listening… lines appear as people speak." : "Start recording (red dot under the video) to transcribe the visit. The scribe turns the conversation into a draft note.")}
              </li>
            )}
          </ul>
        )}
      </div>
      {tab === "chat" && (
        <div className="border-t border-line p-2">
          <div className="mb-1.5 flex gap-1 overflow-x-auto scroll-thin">
            {QUICK.map((q) => (
              <SourceButton key={q} onClick={() => send(q)} className="shrink-0 rounded-full border border-line px-2 py-0.5 text-2xs text-ink-600 hover:border-pulse-500 hover:text-pulse-700">
                {q}
              </SourceButton>
            ))}
          </div>
          <form onSubmit={(e) => { e.preventDefault(); send(); }} className="flex gap-1.5">
            <SourceInput value={text} onChange={(e) => setText(e.target.value)} placeholder="Message the patient" className="h-8 min-w-0 flex-1 rounded-md border border-line px-2.5 text-[13px] focus:border-pulse-500 focus:outline-none" />
            <Button size="sm" variant="primary" type="submit" aria-label="Send" icon={<Send className="h-3.5 w-3.5" />} />
          </form>
        </div>
      )}
    </section>
  );
}
