/**
 * One-time mechanical import of the MedBand patient-access SOURCE frontend.
 *
 *   node scripts/medband/import.mjs [--force]
 *
 * Source: reference/frontend/medband-patient-access-1/medband/src (read only; override with MEDBAND_REFERENCE_ROOT).
 * Copies the nine pages, the patient/encounter/ui components and the pure lib modules (types, search, admission, followup,
 * encounter-config) into packages/reference-medband/src, applying only mechanical rewrites:
 *   - "@/..." aliases become relative paths
 *   - next/link -> ReferenceLink, next/navigation -> src/lib/navigation (host path/router), `use(params)`/useParams -> explicit props
 *   - native button/input/textarea/select/table elements -> shared Source controls and Table (src/components/controls)
 *   - lib/master-data globals -> `useMaster()` destructured inside each component (scope-bound registry, no module state)
 *   - fmtDate/fmtDateTime/fmtTime/ageOf/relativeDay -> `useMedbandFormat()` (host preferences); `api` -> `useMedbandApi()`
 *   - English copy: JSX text runs become <LocalizedText message values>, copy template literals and string leaves become tr(...)
 * Not copied: the standalone shell (layout, AppShell, Sidebar, DemoReset), global CSS (generated by scripts/medband/styles.mjs),
 * lib/api, lib/master-data, lib/store, lib/utils, lib/contract (hand adapted onto the host transport) and everything under
 * src/server and src/app/api (the backend).
 * Existing files are kept unless --force is given, so later hand adaptation is never overwritten.
 */
import {existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync} from 'node:fs';
import {dirname, join, relative, resolve} from 'node:path';
import ts from 'typescript';

const root = resolve(import.meta.dirname, '../..');
const source = process.env.MEDBAND_REFERENCE_ROOT ?? '/home/pepadmin/pb/saas/reference/frontend/medband-patient-access-1/medband/src';
const target = join(root, 'packages/reference-medband/src');
const force = process.argv.includes('--force');
const rel = (from, to) => { const v = relative(dirname(from), to).split('\\').join('/'); return v.startsWith('.') ? v : './' + v; };

const files = [
  'app/page.tsx', 'app/patients/page.tsx', 'app/patients/new/page.tsx', 'app/patients/[id]/page.tsx',
  'app/encounters/page.tsx', 'app/encounters/new/page.tsx', 'app/admissions/page.tsx', 'app/admissions/new/page.tsx', 'app/episodes/page.tsx',
  'components/encounter/complaint-picker.tsx', 'components/encounter/patient-context.tsx', 'components/encounter/type-tag.tsx',
  'components/patient/coverage-editor.tsx', 'components/patient/patient-picker.tsx', 'components/patient/quick-register.tsx', 'components/patient/wristband.tsx',
  'components/ui/form.tsx', 'components/ui/overlay.tsx', 'components/ui/primitives.tsx',
  'lib/types.ts', 'lib/search.ts', 'lib/admission.ts', 'lib/followup.ts', 'lib/encounter-config.ts',
];

import {localizeFile,injectHooks} from '../reference-import-transforms.mjs';
const MASTER = ['PAYERS', 'TPAS', 'NETWORKS', 'PLANS', 'DEPARTMENTS', 'PRACTITIONERS', 'WARDS', 'SERVICES', 'PACKAGES', 'COMPLAINTS', 'COUNTERS',
  'payer', 'tpa', 'network', 'plan', 'department', 'practitioner', 'ward', 'healthPackage', 'complaint', 'counter',
  'networksFor', 'plansFor', 'tpasFor', 'practitionersFor', 'wardsForCategory'];
const FORMAT = ['fmtDate', 'fmtDateTime', 'fmtTime', 'ageOf', 'relativeDay'];
const CONTROLS = {button: 'SourceButton', input: 'SourceInput', textarea: 'SourceTextarea', select: 'SourceSelect', table: 'Table', thead: 'TableHeader', tbody: 'TableBody', tr: 'TableRow', th: 'TableHead', td: 'TableCell'};
function rewrite(text, dest) {
  const needs = {master: false, format: false, api: false, tr: false, lt: false};
  const extraImports = [];
  const typeImports = [];
  // 1. imports
  text = text.replace(/from "@\/([^"]+)"/g, (_m, p) => `from "${rel(dest, join(target, p))}"`);
  text = text.replace(/import \{([^}]+)\} from "(\.[^"]*\/lib\/master-data)";\n/, (m, names, path) => {
    const types = [], values = [];
    names.split(',').map(s => s.trim()).filter(Boolean).forEach(n => (n.startsWith('type ') ? types.push(n.slice(5)) : values.push(n)));
    if (types.length) typeImports.push(`import type { ${types.join(', ')} } from "${path.replace('master-data', 'master')}";`);
    return '';
  });
  text = text.replace(/import \{([^}]+)\} from "(\.[^"]*\/lib\/utils)";/, (m, names, path) => {
    const keep = names.split(',').map(s => s.trim()).filter(n => n && !FORMAT.includes(n));
    return keep.length ? `import { ${keep.join(', ')} } from "${path}";` : '';
  });
  text = text.replace(/import \{ api \} from "(\.[^"]*\/lib\/api)";\n/, '');
  text = text.replace(/import Link from "next\/link";/, 'import { ReferenceLink as Link } from "@pepbits/reference-host";');
  text = text.replace(/from "next\/navigation"/, `from "${rel(dest, join(target, 'lib/navigation'))}"`);
  if (/\.tsx$/.test(dest)) {
    // 2. native elements -> shared controls
    const used = [];
    for (const [tag, name] of Object.entries(CONTROLS)) {
      const open = new RegExp(`<(/?)${tag}(?=[\\s>/])`, 'g');
      if (open.test(text)) { text = text.replace(open, `<$1${name}`); used.push(name); }
    }
    if (used.length) extraImports.push(`import { ${used.join(', ')} } from "${rel(dest, join(target, 'components/controls'))}";`);
    // 3. copy
    const loc = localizeFile(text, dest);
    text = loc.text;
    needs.tr = loc.flags.tr; needs.lt = loc.flags.lt;
  }
  let orphans = [];
  if (/\.tsx?$/.test(dest) && !/lib\/(types|search|encounter-config)\.ts$/.test(dest)) {
    const wanted = {master: MASTER, format: FORMAT, api: ['api'], tr: ['tr']};
    if (/\/ui\/(form|overlay|primitives)\.tsx$/.test(dest)) delete wanted.api;
    const r = injectHooks(text, dest, wanted);
    text = r.text; orphans = r.orphans;
    const sf = parse(text, dest);
    const has = re => re.test(text.replace(/^import .*$/gm, ''));
    if (/useMaster\(\)/.test(text)) extraImports.push(`import { useMaster } from "${rel(dest, join(target, 'lib/master'))}";`);
    if (/useMedbandFormat\(\)/.test(text)) extraImports.push(`import { useMedbandFormat } from "${rel(dest, join(target, 'lib/format'))}";`);
    if (/useMedbandApi\(\)/.test(text)) extraImports.push(`import { useMedbandApi } from "${rel(dest, join(target, 'lib/store'))}";`);
    const ops = [];
    if (has(/<LocalizedText\b/)) ops.push('LocalizedText');
    if (/useLocalization\(\)/.test(text)) ops.push('useLocalization');
    if (ops.length) extraImports.push(`import { ${ops.join(', ')} } from "@pepbits/ops-ui";`);
  }
  if (typeImports.length || extraImports.length) {
    const lines = text.split('\n');
    let last = -1, inBlock = false;
    lines.forEach((l, i) => { if (/^import\b/.test(l)) { inBlock = !/from ".*";?$/.test(l) && !/^import ".*";?$/.test(l); last = i; } else if (inBlock) { last = i; if (/from ".*";?$/.test(l)) inBlock = false; } });
    lines.splice(last + 1, 0, ...typeImports, ...extraImports);
    text = lines.join('\n');
  }
  // 4. dynamic route params arrive as explicit props
  text = text.replace(/import \{ useParams \} from "[^"]+";\n/, '');
  return {text, orphans};
}

for (const relPath of files) {
  const file = join(source, relPath);
  const dest = join(target, relPath);
  if (existsSync(dest) && !force) { console.log('keep   ', relative(root, dest)); continue; }
  const {text, orphans} = rewrite(readFileSync(file, 'utf8'), dest);
  mkdirSync(dirname(dest), {recursive: true});
  writeFileSync(dest, text);
  console.log('write  ', relative(root, dest), orphans.length ? '\n   NEEDS HAND FIX: ' + orphans.join('; ') : '');
}
