import React from 'react';import {render,screen,fireEvent,waitFor,cleanup} from '@testing-library/react';import {afterEach,describe,it,expect,vi} from 'vitest';
import {DEFAULT_PREFERENCES,MEDSLOT_REFERENCE,referenceNavigationTarget} from '@pepbits/erp-config';import {ReferenceHostProvider,type ReferenceHost} from '@pepbits/reference-host';import {ReferenceMedslotModule} from './module';import {MedslotApiProvider,useSourceApi} from './lib/api';import {useMedslotFormat} from './lib/format';import fixtures from './__fixtures__/api.json';
afterEach(cleanup);const data=fixtures as Record<string,any>;
function host(handler?:(p:string,i?:RequestInit)=>Promise<any>):ReferenceHost{return {scope:{tenantId:'synthetic',applicationId:'nexora',branchId:'hq',userId:'test',roles:['enterprise-admin'],moduleId:'reference-medslot'},preferences:{...DEFAULT_PREFERENCES},navigate:vi.fn(),request:vi.fn(async(p,i)=>{if(handler)return handler(p,i);const key=p.replace(/^\/api/,'').split('?')[0];if(!(key in data))throw Error('Unmapped synthetic API fixture '+key);return structuredClone(data[key]);})};}
describe('MedSlot imported pages and shared host contracts',()=>{
 it('registers 12 menu destinations plus two durable detail routes',()=>{expect(MEDSLOT_REFERENCE.pages).toHaveLength(14);expect(MEDSLOT_REFERENCE.pages.filter(p=>!p.path.includes('[id]'))).toHaveLength(12);for(const entity of ['patients','resources'])expect(referenceNavigationTarget('reference-medslot','/'+entity+'/42').recordId).toBe('/'+entity+'/42');});
 it.each([['/','How the hospital is running'],['/book','Book an appointment'],['/calendar',undefined],['/appointments','Appointments'],['/patients','Patients'],['/resources','Resources and schedules'],['/services','Services'],['/departments','Departments'],['/holidays','Holidays'],['/notifications','Notifications'],['/settings','Users and settings'],['/audit','Audit log']])('renders original %s without a secondary login',async(path,title)=>{const h=host();render(<ReferenceMedslotModule path={path} host={h}/>);await waitFor(()=>expect(document.querySelector('.reference-medslot main')).toBeTruthy());await waitFor(()=>expect(h.request).toHaveBeenCalledWith('/api/settings',expect.any(Object)));expect(screen.queryByText('Sign in')).toBeNull();expect(document.querySelector('.reference-medslot')).toBeTruthy();await screen.findByRole('heading',{name:title});});
 it('recovers a denied identity without presenting seeded frontend records',async()=>{let allow=false;const h=host(async p=>{if(!allow)throw Object.assign(Error('Synthetic denial'),{status:403});return data[p.replace(/^\/api/,'')];});render(<ReferenceMedslotModule path="/" host={h}/>);await screen.findByRole('alert');expect(document.querySelector('main')).toBeNull();allow=true;fireEvent.click(screen.getByText('Try again'));await waitFor(()=>expect(document.querySelector('main')).toBeTruthy());});
 it('retains idempotency identity for ambiguous booking retries',async()=>{const keys:string[]=[];const h=host(async(p,i)=>{keys.push(new Headers(i?.headers).get('Idempotency-Key')!);if(keys.length===1)throw Object.assign(Error('Lost response'),{status:503});return {id:1};});function Write(){const api=useSourceApi();return <button onClick={()=>void api('/appointments',{method:'POST',json:{reason:'Synthetic'}}).catch(()=>{})}>Book synthetic</button>;};render(<ReferenceHostProvider host={h}><MedslotApiProvider><Write/></MedslotApiProvider></ReferenceHostProvider>);fireEvent.click(screen.getByText('Book synthetic'));await waitFor(()=>expect(keys).toHaveLength(1));fireEvent.click(screen.getByText('Book synthetic'));await waitFor(()=>expect(keys).toHaveLength(2));expect(keys[0]).toBe(keys[1]);});
 it('keeps facility wall-clock times and host date/time preferences',()=>{function Format(){const f=useMedslotFormat();return <p>{f.fmtDateTime('2026-10-02T14:30')}</p>};const h=host();h.preferences={...h.preferences,dateFormat:'dmy',timeFormat:'12h'};render(<ReferenceHostProvider host={h}><Format/></ReferenceHostProvider>);expect(screen.getByText(/02\/10\/2026/).textContent).toContain('2:30');});
 it('shows a scoped shared patient dialog and handles Escape',async()=>{render(<ReferenceMedslotModule path="/patients" host={host()}/>);fireEvent.click(await screen.findByRole('button',{name:/Register patient/i}));await screen.findByRole('dialog');fireEvent.keyDown(window,{key:'Escape'});await waitFor(()=>expect(screen.queryByRole('dialog')).toBeNull());});
});
