import type {
  AllergenOption,
  Catalog,
  Drug,
  IcdCode,
  NoteTemplate,
  OrderableItem,
  OrderSet,
  ScoreDefinition,
} from "./types.ts";

const icd = (code: string, display: string, keywords: string): IcdCode => ({
  code,
  display,
  keywords: keywords.split(",").map((k) => k.trim()),
});

export const ICD: IcdCode[] = [
  icd("J06.9", "Acute upper respiratory infection, unspecified", "cold, uri, runny nose, sore throat, cough, congestion"),
  icd("J02.9", "Acute pharyngitis, unspecified", "sore throat, pharyngitis, throat pain"),
  icd("J02.0", "Streptococcal pharyngitis", "strep, sore throat, tonsil exudate"),
  icd("J03.90", "Acute tonsillitis, unspecified", "tonsillitis, tonsils, sore throat"),
  icd("J01.90", "Acute sinusitis, unspecified", "sinusitis, facial pain, sinus, congestion"),
  icd("J20.9", "Acute bronchitis, unspecified", "bronchitis, cough, sputum"),
  icd("J18.9", "Pneumonia, unspecified organism", "pneumonia, fever, cough, shortness of breath"),
  icd("J45.909", "Unspecified asthma, uncomplicated", "asthma, wheeze"),
  icd("J45.901", "Unspecified asthma with (acute) exacerbation", "asthma attack, wheeze, breathless"),
  icd("J44.1", "COPD with (acute) exacerbation", "copd, emphysema, breathless"),
  icd("U07.1", "COVID-19", "covid, coronavirus, sars-cov-2, fever, cough"),
  icd("J11.1", "Influenza with other respiratory manifestations", "flu, influenza, fever, body ache"),
  icd("J30.9", "Allergic rhinitis, unspecified", "hay fever, allergic rhinitis, sneezing"),
  icd("R05.9", "Cough, unspecified", "cough"),
  icd("R50.9", "Fever, unspecified", "fever, pyrexia, temperature"),
  icd("R51.9", "Headache, unspecified", "headache"),
  icd("G43.909", "Migraine, unspecified, not intractable", "migraine, headache, aura"),
  icd("R07.9", "Chest pain, unspecified", "chest pain"),
  icd("R06.02", "Shortness of breath", "shortness of breath, dyspnea, breathless"),
  icd("R42", "Dizziness and giddiness", "dizziness, vertigo, lightheaded"),
  icd("R53.83", "Other fatigue", "fatigue, tired, tiredness"),
  icd("R10.9", "Unspecified abdominal pain", "abdominal pain, stomach ache, tummy"),
  icd("R11.2", "Nausea with vomiting, unspecified", "nausea, vomiting"),
  icd("K21.9", "Gastro-esophageal reflux disease without esophagitis", "gerd, reflux, heartburn"),
  icd("A09", "Infectious gastroenteritis and colitis, unspecified", "gastroenteritis, diarrhea, diarrhoea"),
  icd("K59.00", "Constipation, unspecified", "constipation"),
  icd("N39.0", "Urinary tract infection, site not specified", "uti, burning urination, dysuria, frequency"),
  icd("N94.6", "Dysmenorrhea, unspecified", "period pain, dysmenorrhea"),
  icd("I10", "Essential (primary) hypertension", "hypertension, blood pressure, bp, htn"),
  icd("I48.91", "Unspecified atrial fibrillation", "atrial fibrillation, af, palpitations, irregular"),
  icd("I50.9", "Heart failure, unspecified", "heart failure, edema, swelling"),
  icd("E11.9", "Type 2 diabetes mellitus without complications", "diabetes, t2dm, sugar"),
  icd("E11.65", "Type 2 diabetes mellitus with hyperglycemia", "high sugar, hyperglycemia, diabetes"),
  icd("E78.5", "Hyperlipidemia, unspecified", "cholesterol, lipids, hyperlipidemia"),
  icd("E03.9", "Hypothyroidism, unspecified", "hypothyroid, thyroid"),
  icd("E66.9", "Obesity, unspecified", "obesity, weight"),
  icd("D64.9", "Anemia, unspecified", "anemia, anaemia, low hemoglobin"),
  icd("F32.9", "Major depressive disorder, single episode, unspecified", "depression, low mood"),
  icd("F41.1", "Generalized anxiety disorder", "anxiety, worry, gad"),
  icd("F41.0", "Panic disorder", "panic, panic attack"),
  icd("G47.00", "Insomnia, unspecified", "insomnia, sleep, cannot sleep"),
  icd("F17.210", "Nicotine dependence, cigarettes, uncomplicated", "smoking, cigarettes, nicotine"),
  icd("M54.50", "Low back pain, unspecified", "back pain, low back, lumbago"),
  icd("M25.561", "Pain in right knee", "knee pain"),
  icd("M79.10", "Myalgia, unspecified site", "muscle pain, myalgia, body ache"),
  icd("L30.9", "Dermatitis, unspecified", "dermatitis, rash, itchy skin"),
  icd("L20.9", "Atopic dermatitis, unspecified", "eczema, atopic dermatitis"),
  icd("L70.0", "Acne vulgaris", "acne, pimples"),
  icd("L50.9", "Urticaria, unspecified", "hives, urticaria, wheals"),
  icd("B35.4", "Tinea corporis", "ringworm, tinea, fungal"),
  icd("R21", "Rash and other nonspecific skin eruption", "rash, skin"),
  icd("H10.9", "Unspecified conjunctivitis", "pink eye, conjunctivitis, red eye"),
  icd("H66.90", "Otitis media, unspecified, unspecified ear", "ear pain, otitis, ear infection"),
  icd("B34.9", "Viral infection, unspecified", "viral, virus"),
  icd("T78.40XA", "Allergy, unspecified, initial encounter", "allergy, allergic reaction"),
  icd("Z00.00", "Encounter for general adult medical examination without abnormal findings", "checkup, annual, physical"),
  icd("Z09", "Encounter for follow-up examination after completed treatment", "follow up, review"),
  icd("Z76.0", "Encounter for issue of repeat prescription", "refill, repeat prescription"),
  icd("Z71.3", "Dietary counseling and surveillance", "diet, nutrition"),
];

const drug = (
  id: string,
  name: string,
  strength: string,
  form: string,
  drugClass: string,
  defaultDose: string,
  defaultFrequency: string,
  defaultDays: number,
  dosesPerDay: number,
  opts: Partial<Drug> = {},
): Drug => ({
  id,
  name,
  strength,
  form,
  drugClass,
  route: "oral",
  defaultDose,
  defaultFrequency,
  defaultDays,
  unitsPerDose: 1,
  dosesPerDay,
  ...opts,
});

export const DRUGS: Drug[] = [
  drug("paracetamol", "Paracetamol", "500 mg", "tablet", "Analgesic", "1000 mg (2 tablets)", "Every 6 hours as needed", 5, 4, { unitsPerDose: 2 }),
  drug("ibuprofen", "Ibuprofen", "400 mg", "tablet", "NSAID", "400 mg", "Three times daily with food", 5, 3, { allergyClass: "nsaid" }),
  drug("naproxen", "Naproxen", "500 mg", "tablet", "NSAID", "500 mg", "Twice daily with food", 7, 2, { allergyClass: "nsaid" }),
  drug("aspirin", "Aspirin", "75 mg", "tablet", "Antiplatelet", "75 mg", "Once daily", 30, 1, { allergyClass: "nsaid" }),
  drug("amoxicillin", "Amoxicillin", "500 mg", "capsule", "Penicillin antibiotic", "500 mg", "Three times daily", 7, 3, { allergyClass: "penicillin" }),
  drug("amoxiclav", "Amoxicillin-clavulanate", "625 mg", "tablet", "Penicillin antibiotic", "625 mg", "Three times daily", 7, 3, { allergyClass: "penicillin" }),
  drug("phenoxymethylpenicillin", "Penicillin V", "500 mg", "tablet", "Penicillin antibiotic", "500 mg", "Four times daily", 10, 4, { allergyClass: "penicillin" }),
  drug("cephalexin", "Cephalexin", "500 mg", "capsule", "Cephalosporin antibiotic", "500 mg", "Four times daily", 7, 4, { allergyClass: "cephalosporin" }),
  drug("azithromycin", "Azithromycin", "500 mg", "tablet", "Macrolide antibiotic", "500 mg", "Once daily", 3, 1, { allergyClass: "macrolide" }),
  drug("clarithromycin", "Clarithromycin", "500 mg", "tablet", "Macrolide antibiotic", "500 mg", "Twice daily", 7, 2, { allergyClass: "macrolide" }),
  drug("doxycycline", "Doxycycline", "100 mg", "capsule", "Tetracycline antibiotic", "100 mg", "Twice daily", 7, 2),
  drug("ciprofloxacin", "Ciprofloxacin", "500 mg", "tablet", "Fluoroquinolone antibiotic", "500 mg", "Twice daily", 5, 2, { allergyClass: "fluoroquinolone" }),
  drug("nitrofurantoin", "Nitrofurantoin MR", "100 mg", "capsule", "Urinary antibacterial", "100 mg", "Twice daily", 5, 2),
  drug("trimethoprim-smx", "Co-trimoxazole", "960 mg", "tablet", "Sulfonamide antibiotic", "960 mg", "Twice daily", 3, 2, { allergyClass: "sulfonamide" }),
  drug("metronidazole", "Metronidazole", "400 mg", "tablet", "Nitroimidazole antibiotic", "400 mg", "Three times daily", 7, 3),
  drug("fluconazole", "Fluconazole", "150 mg", "capsule", "Antifungal", "150 mg", "Single dose", 1, 1),
  drug("oseltamivir", "Oseltamivir", "75 mg", "capsule", "Antiviral", "75 mg", "Twice daily", 5, 2),
  drug("cetirizine", "Cetirizine", "10 mg", "tablet", "Antihistamine", "10 mg", "Once daily", 14, 1),
  drug("fexofenadine", "Fexofenadine", "180 mg", "tablet", "Antihistamine", "180 mg", "Once daily", 14, 1),
  drug("salbutamol", "Salbutamol inhaler", "100 mcg/dose", "inhaler", "Short-acting beta agonist", "2 puffs", "Every 4–6 hours as needed", 30, 4, { route: "inhaled", unitsPerDose: 0 }),
  drug("budesonide-formoterol", "Budesonide-formoterol inhaler", "200/6 mcg", "inhaler", "ICS-LABA", "1 puff", "Twice daily", 30, 2, { route: "inhaled", unitsPerDose: 0 }),
  drug("prednisolone", "Prednisolone", "5 mg", "tablet", "Corticosteroid", "40 mg (8 tablets)", "Once daily in the morning", 5, 1, { unitsPerDose: 8 }),
  drug("montelukast", "Montelukast", "10 mg", "tablet", "Leukotriene antagonist", "10 mg", "Once daily at night", 30, 1),
  drug("omeprazole", "Omeprazole", "20 mg", "capsule", "Proton pump inhibitor", "20 mg", "Once daily before breakfast", 28, 1),
  drug("ondansetron", "Ondansetron", "4 mg", "tablet", "Antiemetic", "4 mg", "Every 8 hours as needed", 3, 3),
  drug("loperamide", "Loperamide", "2 mg", "capsule", "Antidiarrheal", "2 mg", "After each loose stool, max 8/day", 3, 4),
  drug("ors", "Oral rehydration salts", "1 sachet", "sachet", "Rehydration", "1 sachet in 200 ml water", "After each loose stool", 3, 4),
  drug("metformin", "Metformin", "500 mg", "tablet", "Biguanide", "500 mg", "Twice daily with meals", 90, 2),
  drug("sitagliptin", "Sitagliptin", "100 mg", "tablet", "DPP-4 inhibitor", "100 mg", "Once daily", 90, 1),
  drug("amlodipine", "Amlodipine", "5 mg", "tablet", "Calcium channel blocker", "5 mg", "Once daily", 90, 1),
  drug("losartan", "Losartan", "50 mg", "tablet", "ARB", "50 mg", "Once daily", 90, 1),
  drug("lisinopril", "Lisinopril", "10 mg", "tablet", "ACE inhibitor", "10 mg", "Once daily", 90, 1),
  drug("hydrochlorothiazide", "Hydrochlorothiazide", "25 mg", "tablet", "Thiazide diuretic", "25 mg", "Once daily in the morning", 90, 1, { allergyClass: "sulfonamide" }),
  drug("atorvastatin", "Atorvastatin", "20 mg", "tablet", "Statin", "20 mg", "Once daily at night", 90, 1),
  drug("warfarin", "Warfarin", "5 mg", "tablet", "Vitamin K antagonist", "As per INR", "Once daily", 30, 1),
  drug("apixaban", "Apixaban", "5 mg", "tablet", "DOAC", "5 mg", "Twice daily", 30, 2),
  drug("levothyroxine", "Levothyroxine", "50 mcg", "tablet", "Thyroid hormone", "50 mcg", "Once daily before breakfast", 90, 1),
  drug("sertraline", "Sertraline", "50 mg", "tablet", "SSRI", "50 mg", "Once daily", 30, 1),
  drug("escitalopram", "Escitalopram", "10 mg", "tablet", "SSRI", "10 mg", "Once daily", 30, 1),
  drug("tramadol", "Tramadol", "50 mg", "capsule", "Opioid analgesic", "50 mg", "Every 6 hours as needed", 3, 4, { allergyClass: "opioid" }),
  drug("sumatriptan", "Sumatriptan", "50 mg", "tablet", "Triptan", "50 mg", "At migraine onset, may repeat after 2 h", 30, 1),
  drug("amoxicillin-susp", "Amoxicillin suspension", "250 mg/5 ml", "suspension", "Penicillin antibiotic", "Weight-based", "Three times daily", 5, 3, { allergyClass: "penicillin", unitsPerDose: 0 }),
  drug("hydrocortisone-cream", "Hydrocortisone cream", "1%", "cream", "Topical corticosteroid", "Thin layer", "Twice daily", 7, 2, { route: "topical", unitsPerDose: 0 }),
  drug("emollient", "Emollient cream", "500 g", "cream", "Emollient", "Apply liberally", "Three to four times daily", 30, 3, { route: "topical", unitsPerDose: 0 }),
  drug("clotrimazole", "Clotrimazole cream", "1%", "cream", "Topical antifungal", "Thin layer", "Twice daily", 14, 2, { route: "topical", unitsPerDose: 0 }),
  drug("melatonin", "Melatonin", "3 mg", "tablet", "Sleep aid", "3 mg", "At bedtime", 14, 1),
];

export const INTERACTIONS: { a: string[]; b: string[]; level: "warning" | "critical"; title: string; detail: string }[] = [
  { a: ["warfarin", "apixaban"], b: ["ibuprofen", "naproxen", "aspirin"], level: "critical", title: "Bleeding risk", detail: "Anticoagulant combined with an NSAID or antiplatelet significantly raises bleeding risk. Prefer paracetamol." },
  { a: ["warfarin"], b: ["clarithromycin", "ciprofloxacin", "metronidazole", "fluconazole", "trimethoprim-smx"], level: "critical", title: "INR elevation", detail: "This antimicrobial potentiates warfarin. Choose an alternative or arrange INR check within 3–5 days." },
  { a: ["sertraline", "escitalopram"], b: ["tramadol", "sumatriptan"], level: "critical", title: "Serotonin syndrome risk", detail: "Serotonergic combination. Avoid, or counsel on agitation, tremor and fever." },
  { a: ["sertraline", "escitalopram"], b: ["ibuprofen", "naproxen", "aspirin"], level: "warning", title: "GI bleeding risk", detail: "SSRIs with NSAIDs increase upper GI bleeding. Consider gastroprotection." },
  { a: ["lisinopril"], b: ["losartan"], level: "critical", title: "Dual RAAS blockade", detail: "ACE inhibitor with ARB increases hyperkalemia and kidney injury risk." },
  { a: ["lisinopril", "losartan", "hydrochlorothiazide"], b: ["ibuprofen", "naproxen"], level: "warning", title: "Kidney injury risk", detail: "NSAIDs with antihypertensives reduce renal perfusion. Check renal function if used beyond a few days." },
  { a: ["clarithromycin"], b: ["atorvastatin"], level: "warning", title: "Myopathy risk", detail: "Clarithromycin raises statin levels. Pause atorvastatin during the course." },
  { a: ["azithromycin", "clarithromycin", "ciprofloxacin"], b: ["escitalopram", "ondansetron"], level: "warning", title: "QT prolongation", detail: "Additive QT effect. Avoid in patients with known QT prolongation or electrolyte disturbance." },
];

// Cross-reactivity: allergy class -> drug allergy classes that should warn
export const CROSS_REACTIVITY: Record<string, { cls: string; level: "warning" | "critical" }[]> = {
  penicillin: [
    { cls: "penicillin", level: "critical" },
    { cls: "cephalosporin", level: "warning" },
  ],
  cephalosporin: [{ cls: "cephalosporin", level: "critical" }],
  nsaid: [{ cls: "nsaid", level: "critical" }],
  sulfonamide: [{ cls: "sulfonamide", level: "critical" }],
  macrolide: [{ cls: "macrolide", level: "critical" }],
  fluoroquinolone: [{ cls: "fluoroquinolone", level: "critical" }],
  opioid: [{ cls: "opioid", level: "critical" }],
};

const o = (kind: OrderableItem["kind"], code: string, name: string, group: string, detail: string): OrderableItem => ({
  kind,
  code,
  name,
  group,
  detail,
});

export const ORDERABLES: OrderableItem[] = [
  // Labs (LOINC)
  o("lab", "58410-2", "Complete blood count (CBC)", "Hematology", "EDTA · same day"),
  o("lab", "4537-7", "Erythrocyte sedimentation rate", "Hematology", "EDTA · same day"),
  o("lab", "6301-6", "PT / INR", "Coagulation", "Citrate · 2 h"),
  o("lab", "48065-7", "D-dimer", "Coagulation", "Citrate · 2 h"),
  o("lab", "24323-8", "Comprehensive metabolic panel", "Chemistry", "Serum · same day"),
  o("lab", "51990-0", "Basic metabolic panel", "Chemistry", "Serum · same day"),
  o("lab", "2160-0", "Creatinine and eGFR", "Chemistry", "Serum · same day"),
  o("lab", "24325-3", "Liver function panel", "Chemistry", "Serum · same day"),
  o("lab", "1988-5", "C-reactive protein", "Inflammation", "Serum · 2 h"),
  o("lab", "33959-8", "Procalcitonin", "Inflammation", "Serum · 4 h"),
  o("lab", "4548-4", "Hemoglobin A1c", "Diabetes", "EDTA · 24 h"),
  o("lab", "1558-6", "Fasting glucose", "Diabetes", "Fluoride · same day"),
  o("lab", "57698-3", "Lipid panel", "Cardiometabolic", "Serum · fasting"),
  o("lab", "10839-9", "Troponin I, high sensitivity", "Cardiac", "Serum · 1 h"),
  o("lab", "33762-6", "NT-proBNP", "Cardiac", "Serum · 4 h"),
  o("lab", "3016-3", "TSH", "Endocrine", "Serum · 24 h"),
  o("lab", "3024-7", "Free T4", "Endocrine", "Serum · 24 h"),
  o("lab", "2276-4", "Ferritin", "Hematinics", "Serum · 24 h"),
  o("lab", "2132-9", "Vitamin B12", "Hematinics", "Serum · 48 h"),
  o("lab", "1989-3", "Vitamin D (25-OH)", "Endocrine", "Serum · 48 h"),
  o("lab", "3040-3", "Lipase", "Chemistry", "Serum · 2 h"),
  o("lab", "2106-3", "hCG pregnancy test", "Reproductive", "Urine · 1 h"),
  o("lab", "24356-8", "Urinalysis with microscopy", "Urine", "Midstream · 2 h"),
  o("lab", "630-4", "Urine culture", "Microbiology", "Midstream · 48 h"),
  o("lab", "600-7", "Blood culture", "Microbiology", "2 sets · 5 days"),
  o("lab", "625-4", "Stool culture", "Microbiology", "Stool · 72 h"),
  o("lab", "18481-2", "Rapid strep A antigen", "Microbiology", "Throat swab · 15 min"),
  o("lab", "94500-6", "SARS-CoV-2 PCR", "Respiratory", "Nasopharyngeal swab · 24 h"),
  o("lab", "92142-9", "Influenza A/B PCR", "Respiratory", "Nasopharyngeal swab · 24 h"),
  o("lab", "9343-4", "Albumin/creatinine ratio, urine", "Urine", "Spot urine · 24 h"),
  // Imaging
  o("imaging", "IMG-CXR", "Chest X-ray, PA and lateral", "X-ray", "No preparation"),
  o("imaging", "IMG-KNEE", "Knee X-ray, 2 views", "X-ray", "No preparation"),
  o("imaging", "IMG-LSPINE-XR", "Lumbar spine X-ray", "X-ray", "No preparation"),
  o("imaging", "IMG-USABD", "Ultrasound abdomen", "Ultrasound", "Fast 6 hours"),
  o("imaging", "IMG-USPEL", "Ultrasound pelvis", "Ultrasound", "Full bladder"),
  o("imaging", "IMG-USTHY", "Ultrasound thyroid", "Ultrasound", "No preparation"),
  o("imaging", "IMG-DVT", "Doppler, lower limb veins", "Ultrasound", "No preparation"),
  o("imaging", "IMG-ECHO", "Transthoracic echocardiogram", "Cardiac", "No preparation"),
  o("imaging", "IMG-CTH", "CT head without contrast", "CT", "No preparation"),
  o("imaging", "IMG-CTPA", "CT pulmonary angiogram", "CT", "Contrast · check eGFR"),
  o("imaging", "IMG-CTAP", "CT abdomen and pelvis with contrast", "CT", "Contrast · check eGFR"),
  o("imaging", "IMG-MRIL", "MRI lumbar spine", "MRI", "Screen for implants"),
  o("imaging", "IMG-MRIB", "MRI brain", "MRI", "Screen for implants"),
  o("imaging", "IMG-DEXA", "DEXA bone density", "Other", "No calcium 24 h before"),
  // Procedures and diagnostics
  o("procedure", "PRC-ECG", "12-lead ECG", "Cardiac", "Clinic or home kit"),
  o("procedure", "PRC-HOLTER", "24-hour Holter monitor", "Cardiac", "Device couriered"),
  o("procedure", "PRC-ABPM", "Ambulatory BP monitoring, 24 h", "Cardiac", "Device couriered"),
  o("procedure", "PRC-SPIRO", "Spirometry with reversibility", "Respiratory", "Clinic visit"),
  o("procedure", "PRC-PEF", "Home peak flow diary, 2 weeks", "Respiratory", "Patient app"),
  o("procedure", "PRC-SLEEP", "Home sleep apnea test", "Sleep", "Device couriered"),
  o("procedure", "PRC-FLUVAX", "Influenza vaccination", "Preventive", "Clinic or pharmacy"),
  o("procedure", "PRC-BIOPSY", "Skin punch biopsy", "Dermatology", "Clinic visit"),
  o("procedure", "PRC-EAR", "Ear microsuction", "ENT", "Clinic visit"),
  // Referrals
  o("referral", "REF-ED", "Emergency department, same day", "Urgent", "In-person, immediate"),
  o("referral", "REF-CARD", "Cardiology", "Medical", "Specialist consult"),
  o("referral", "REF-PULM", "Pulmonology", "Medical", "Specialist consult"),
  o("referral", "REF-GI", "Gastroenterology", "Medical", "Specialist consult"),
  o("referral", "REF-ENDO", "Endocrinology", "Medical", "Specialist consult"),
  o("referral", "REF-NEURO", "Neurology", "Medical", "Specialist consult"),
  o("referral", "REF-DERM", "Dermatology", "Medical", "Specialist consult"),
  o("referral", "REF-ENT", "ENT", "Surgical", "Specialist consult"),
  o("referral", "REF-ORTHO", "Orthopedics", "Surgical", "Specialist consult"),
  o("referral", "REF-PSY", "Psychiatry", "Mental health", "Specialist consult"),
  o("referral", "REF-CBT", "Psychological therapy (CBT)", "Mental health", "Teletherapy available"),
  o("referral", "REF-PHYSIO", "Physiotherapy", "Allied health", "Virtual or in-person"),
  o("referral", "REF-DIET", "Dietitian", "Allied health", "Virtual"),
  // Nursing
  o("nursing", "NUR-RECHECK", "Recheck vitals via patient device in 30 min", "Monitoring", "Remote"),
  o("nursing", "NUR-BPDIARY", "Home BP diary, twice daily for 7 days", "Monitoring", "Patient app"),
  o("nursing", "NUR-GLUC", "Capillary glucose four times daily for 3 days", "Monitoring", "Patient app"),
  o("nursing", "NUR-CALL24", "Nurse follow-up call in 24 hours", "Follow-up", "Phone"),
  o("nursing", "NUR-CALL48", "Medication adherence call in 48 hours", "Follow-up", "Phone"),
  o("nursing", "NUR-INHALER", "Inhaler technique teaching", "Education", "Video"),
  o("nursing", "NUR-FEVER", "Fever and hydration education", "Education", "Patient app"),
  o("nursing", "NUR-WOUND", "Wound photo upload every 2 days", "Monitoring", "Patient app"),
  o("nursing", "NUR-HOMELAB", "Home phlebotomy visit", "Sample collection", "Scheduled"),
  o("nursing", "NUR-FALL", "Falls risk assessment", "Assessment", "Video"),
];

export const ORDER_SETS: OrderSet[] = [
  { id: "os-fever", name: "Fever with cough", description: "Febrile respiratory illness workup", orders: ["58410-2", "1988-5", "94500-6", "92142-9", "IMG-CXR", "NUR-FEVER", "NUR-RECHECK"], drugs: ["paracetamol"], diagnoses: ["R50.9", "R05.9"], scores: ["news2"] },
  { id: "os-throat", name: "Sore throat", description: "Centor-guided pharyngitis pathway", orders: ["18481-2"], drugs: ["paracetamol"], diagnoses: ["J02.9"], scores: ["centor"] },
  { id: "os-htn", name: "Hypertension review", description: "Annual hypertension bundle", orders: ["51990-0", "57698-3", "9343-4", "PRC-ECG", "NUR-BPDIARY"], drugs: [], diagnoses: ["I10"], scores: [] },
  { id: "os-dm", name: "Diabetes review", description: "Glycemic and complication screening", orders: ["4548-4", "24323-8", "57698-3", "9343-4", "2132-9", "REF-DIET"], drugs: [], diagnoses: ["E11.9"], scores: [] },
  { id: "os-chest", name: "Chest pain, remote", description: "Rule out acute coronary syndrome", orders: ["PRC-ECG", "10839-9", "48065-7", "REF-ED"], drugs: [], diagnoses: ["R07.9"], scores: ["news2"] },
  { id: "os-mood", name: "Low mood or anxiety", description: "Screen, exclude organic cause, refer", orders: ["3016-3", "58410-2", "REF-CBT", "NUR-CALL48"], drugs: [], diagnoses: ["F41.1"], scores: ["phq9", "gad7"] },
  { id: "os-uti", name: "Uncomplicated UTI", description: "Female, non-pregnant, no red flags", orders: ["24356-8", "630-4"], drugs: ["nitrofurantoin"], diagnoses: ["N39.0"], scores: [] },
  { id: "os-dizzy", name: "Dizziness in older adult", description: "Cardiac, metabolic and falls workup", orders: ["PRC-ECG", "58410-2", "51990-0", "6301-6", "PRC-HOLTER", "NUR-FALL"], drugs: [], diagnoses: ["R42"], scores: ["news2"] },
];

export const TEMPLATES: NoteTemplate[] = [
  {
    id: "tpl-general",
    name: "General consultation",
    soap: {
      subjective: "Presenting complaint:\nHistory of presenting complaint:\nRelevant history:\nMedications reviewed:\n",
      objective: "Seen via video. General appearance:\nRemote vitals:\nObserved examination:\n",
      assessment: "",
      plan: "Investigations:\nTreatment:\nSafety-netting advice given:\nFollow-up:\n",
    },
  },
  {
    id: "tpl-uri",
    name: "Respiratory infection",
    soap: {
      subjective: "Cough for _ days, fever _, sputum _, breathlessness _. No chest pain, no haemoptysis.\n",
      objective: "Speaking in full sentences. No visible respiratory distress on video. Remote SpO2 _ %, RR _.\n",
      assessment: "",
      plan: "Antipyretics, fluids, rest. Return if breathless, chest pain, confusion or SpO2 below 94%.\n",
    },
  },
  {
    id: "tpl-htn",
    name: "Hypertension follow-up",
    soap: {
      subjective: "Home BP average _/_. Adherence _. Side effects _. Headache, visual change, chest pain: none.\n",
      objective: "Remote BP _/_, HR _.\n",
      assessment: "Essential hypertension, control: _\n",
      plan: "Continue / titrate _. Home BP diary 7 days. Annual bloods.\n",
    },
  },
  {
    id: "tpl-dm",
    name: "Diabetes review",
    soap: {
      subjective: "Home glucose range _. Hypos _. Diet and activity _. Foot or vision symptoms _.\n",
      objective: "Weight _ kg. Remote BP _/_.\n",
      assessment: "Type 2 diabetes, control: _\n",
      plan: "HbA1c, renal function, lipids, urine ACR. Dietitian referral offered.\n",
    },
  },
  {
    id: "tpl-mh",
    name: "Mental health review",
    soap: {
      subjective: "Mood _. Sleep _. Appetite _. Concentration _. Thoughts of self-harm: asked, _.\n",
      objective: "Appearance and behaviour on video _. Speech _. Affect _.\n",
      assessment: "",
      plan: "PHQ-9 / GAD-7 recorded. Crisis line shared. Review in 2–4 weeks.\n",
    },
  },
  {
    id: "tpl-skin",
    name: "Skin, photo-assisted",
    soap: {
      subjective: "Rash for _ days. Itch _. Triggers _. Spread _.\n",
      objective: "Lesions on video and uploaded photos: distribution _, morphology _.\n",
      assessment: "",
      plan: "Emollients, topical treatment. Upload photo in 7 days.\n",
    },
  },
];

export const ALLERGENS: AllergenOption[] = [
  { substance: "Penicillin", category: "drug", allergyClass: "penicillin" },
  { substance: "Amoxicillin", category: "drug", allergyClass: "penicillin" },
  { substance: "Cephalosporins", category: "drug", allergyClass: "cephalosporin" },
  { substance: "Sulfonamides", category: "drug", allergyClass: "sulfonamide" },
  { substance: "NSAIDs", category: "drug", allergyClass: "nsaid" },
  { substance: "Aspirin", category: "drug", allergyClass: "nsaid" },
  { substance: "Macrolides", category: "drug", allergyClass: "macrolide" },
  { substance: "Fluoroquinolones", category: "drug", allergyClass: "fluoroquinolone" },
  { substance: "Codeine / opioids", category: "drug", allergyClass: "opioid" },
  { substance: "Iodinated contrast", category: "drug", allergyClass: "contrast" },
  { substance: "Latex", category: "environment" },
  { substance: "Adhesive tape", category: "environment" },
  { substance: "Pollen", category: "environment" },
  { substance: "Dust mite", category: "environment" },
  { substance: "Cat dander", category: "environment" },
  { substance: "Bee venom", category: "environment" },
  { substance: "Peanut", category: "food" },
  { substance: "Tree nuts", category: "food" },
  { substance: "Shellfish", category: "food" },
  { substance: "Egg", category: "food" },
  { substance: "Cow's milk", category: "food" },
  { substance: "Soy", category: "food" },
  { substance: "Wheat", category: "food" },
];

const opts03 = [
  { label: "Not at all", points: 0 },
  { label: "Several days", points: 1 },
  { label: "More than half the days", points: 2 },
  { label: "Nearly every day", points: 3 },
];
const yesNo = (pts = 1) => [
  { label: "No", points: 0 },
  { label: "Yes", points: pts },
];

export const SCORES: ScoreDefinition[] = [
  {
    key: "news2",
    name: "NEWS2",
    purpose: "Acute illness severity, auto-calculated from latest vitals",
    auto: true,
    items: [],
    bands: [
      { min: 0, band: "low", interpretation: "Low risk. Routine monitoring." },
      { min: 5, band: "moderate", interpretation: "Medium risk. Urgent clinical review." },
      { min: 7, band: "high", interpretation: "High risk. Emergency assessment, consider ED." },
    ],
  },
  {
    key: "phq9",
    name: "PHQ-9",
    purpose: "Depression severity over the last 2 weeks",
    items: [
      "Little interest or pleasure in doing things",
      "Feeling down, depressed, or hopeless",
      "Trouble falling or staying asleep, or sleeping too much",
      "Feeling tired or having little energy",
      "Poor appetite or overeating",
      "Feeling bad about yourself",
      "Trouble concentrating",
      "Moving or speaking slowly, or being restless",
      "Thoughts that you would be better off dead or of hurting yourself",
    ].map((label, i) => ({ id: `q${i + 1}`, label, options: opts03 })),
    bands: [
      { min: 0, band: "low", interpretation: "Minimal depression" },
      { min: 5, band: "low", interpretation: "Mild depression" },
      { min: 10, band: "moderate", interpretation: "Moderate depression" },
      { min: 15, band: "high", interpretation: "Moderately severe depression" },
      { min: 20, band: "high", interpretation: "Severe depression" },
    ],
  },
  {
    key: "gad7",
    name: "GAD-7",
    purpose: "Anxiety severity over the last 2 weeks",
    items: [
      "Feeling nervous, anxious, or on edge",
      "Not being able to stop or control worrying",
      "Worrying too much about different things",
      "Trouble relaxing",
      "Being so restless that it is hard to sit still",
      "Becoming easily annoyed or irritable",
      "Feeling afraid as if something awful might happen",
    ].map((label, i) => ({ id: `q${i + 1}`, label, options: opts03 })),
    bands: [
      { min: 0, band: "low", interpretation: "Minimal anxiety" },
      { min: 5, band: "low", interpretation: "Mild anxiety" },
      { min: 10, band: "moderate", interpretation: "Moderate anxiety" },
      { min: 15, band: "high", interpretation: "Severe anxiety" },
    ],
  },
  {
    key: "centor",
    name: "Centor (McIsaac)",
    purpose: "Probability of streptococcal pharyngitis",
    items: [
      { id: "exudate", label: "Tonsillar exudate or swelling", options: yesNo() },
      { id: "nodes", label: "Tender anterior cervical nodes", options: yesNo() },
      { id: "fever", label: "Temperature above 38 °C", options: yesNo() },
      { id: "nocough", label: "Absence of cough", options: yesNo() },
      {
        id: "age",
        label: "Age",
        options: [
          { label: "3–14 years", points: 1 },
          { label: "15–44 years", points: 0 },
          { label: "45 years or older", points: -1 },
        ],
      },
    ],
    bands: [
      { min: -1, band: "low", interpretation: "Low probability. No test or antibiotic needed." },
      { min: 2, band: "moderate", interpretation: "Intermediate. Rapid strep test, treat if positive." },
      { min: 4, band: "high", interpretation: "High probability. Test, or treat empirically." },
    ],
  },
  {
    key: "curb65",
    name: "CRB-65",
    purpose: "Pneumonia severity for community settings",
    items: [
      { id: "confusion", label: "New confusion", options: yesNo() },
      { id: "rr", label: "Respiratory rate 30 or more", options: yesNo() },
      { id: "bp", label: "Systolic below 90 or diastolic 60 or less", options: yesNo() },
      { id: "age", label: "Age 65 or older", options: yesNo() },
    ],
    bands: [
      { min: 0, band: "low", interpretation: "Low risk. Consider home treatment." },
      { min: 1, band: "moderate", interpretation: "Intermediate. Consider hospital assessment." },
      { min: 3, band: "high", interpretation: "High risk. Urgent hospital admission." },
    ],
  },
];

export const SYMPTOMS = [
  "Fever", "Cough", "Sore throat", "Runny nose", "Headache", "Shortness of breath", "Chest pain",
  "Dizziness", "Fatigue", "Nausea", "Vomiting", "Diarrhea", "Abdominal pain", "Rash", "Itching",
  "Back pain", "Joint pain", "Burning urination", "Ear pain", "Palpitations", "Low mood", "Anxiety",
  "Trouble sleeping", "High blood pressure reading", "High sugar reading", "Medication refill",
];

export const SPECIALTIES = ["General medicine", "Cardiology", "Psychiatry", "Pediatrics", "Dermatology"];

export function getCatalog(): Catalog {
  return {
    icd: ICD,
    drugs: DRUGS,
    orderables: ORDERABLES,
    orderSets: ORDER_SETS,
    templates: TEMPLATES,
    allergens: ALLERGENS,
    scores: SCORES,
    symptoms: SYMPTOMS,
    specialties: SPECIALTIES,
  };
}
