import {act, renderHook, waitFor} from "@testing-library/react";
import {expect, test, vi} from "vitest";
import type {ClinicalTemplateAdapter} from "@pepbits/erp-data";
import type {PatientFilters, PatientSearchResult, PatientSummary} from "@pepbits/erp-config";
import {usePatientSearch} from "./query-search";
const row = (id: string) => ({id, name: `Synthetic ${id}`} as PatientSummary);
const page = (number: number, ids: string[], hasMore = true): PatientSearchResult => ({page:number,pageSize:20,rows:ids.map(row),total:ids.length,hasMore});
const filters: PatientFilters = {q:"Synthetic",page:1,pageSize:20};
test("scroll appends unique records; concurrent observer callbacks issue one request and failed pages retry", async () => {
  let resolve!: (value: PatientSearchResult) => void;
  const search = vi.fn().mockResolvedValueOnce(page(1,["1","2"])).mockImplementationOnce(() => new Promise(r => {resolve=r;})).mockRejectedValueOnce(new Error("offline")).mockResolvedValueOnce(page(3,["4"],false));
  const adapter = {search} as unknown as ClinicalTemplateAdapter;
  const {result} = renderHook(() => usePatientSearch(adapter,filters,true));
  await waitFor(() => expect(result.current.value?.rows).toHaveLength(2));
  act(() => {result.current.more();result.current.more();});
  expect(search).toHaveBeenCalledTimes(2);
  await act(async () => resolve(page(2,["2","3"])));
  expect(result.current.value?.rows.map(r => r.id)).toEqual(["1","2","3"]);
  act(() => result.current.more());
  await waitFor(() => expect(result.current.error).toBeTruthy());
  expect(result.current.value?.rows).toHaveLength(3);
  act(() => result.current.retry());
  await waitFor(() => expect(result.current.value?.rows).toHaveLength(4));
  expect(search.mock.calls[2][0].page).toBe(3);
  expect(search.mock.calls[3][0].page).toBe(3);
  act(() => result.current.more());
  expect(search).toHaveBeenCalledTimes(4);
});
test("changing or clearing criteria aborts requests and rejects stale results even when an adapter ignores abort", async () => {
  const pending: ((value: PatientSearchResult) => void)[] = [];
  const search = vi.fn().mockImplementation(() => new Promise(r => pending.push(r)));
  const adapter = {search} as unknown as ClinicalTemplateAdapter;
  const {result,rerender,unmount} = renderHook(({applied}: {applied: PatientFilters | null}) => usePatientSearch(adapter,applied,true),{initialProps:{applied:filters as PatientFilters|null}});
  rerender({applied:{...filters,q:"Other"}});
  expect(search.mock.calls[0][1].signal.aborted).toBe(true);
  await act(async () => pending[1](page(1,["new"])));
  await act(async () => pending[0](page(1,["stale"])));
  expect(result.current.value?.rows[0].id).toBe("new");
  rerender({applied:null});
  expect(search.mock.calls[1][1].signal.aborted).toBe(true);
  expect(result.current.value).toBeNull();
  unmount();
});
