// Master data used to seed SurgiSuite. Fees are illustrative, not a payer schedule.

export const LOOKUPS: Record<string, string[]> = {
  CASE_CLASS: ["Elective", "Urgent", "Emergency"],
  OP_TYPE: ["Major", "Intermediate", "Minor", "Day Care"],
  PROC_ROLE: ["Primary", "Secondary", "Add-on"],
  APPROACH: ["Open", "Laparoscopic", "Robotic-assisted", "Endoscopic", "Arthroscopic", "Percutaneous", "Microscopic"],
  ANESTHESIA: [
    "General (ETT)", "General (LMA)", "Spinal", "Epidural", "Combined spinal-epidural",
    "Peripheral nerve block", "Monitored anesthesia care", "Local",
  ],
  POSITION: ["Supine", "Prone", "Lateral (left)", "Lateral (right)", "Lithotomy", "Beach chair", "Trendelenburg", "Reverse Trendelenburg"],
  WOUND_CLASS: ["I", "II", "III", "IV"],
  ASA: ["I", "II", "III", "IV", "V", "IE", "IIE", "IIIE", "IVE"],
  LATERALITY: ["N/A", "Left", "Right", "Bilateral"],
  MODIFIER: ["22", "50", "51", "59", "62", "78", "79", "80", "LT", "RT"],
  DELAY_REASON: [
    "Patient arrived late", "Surgeon late", "Anesthesia delay", "Equipment not ready", "Previous case overran",
    "Bed not available", "Incomplete workup", "Instrument tray not sterile",
  ],
  CANCEL_REASON: [
    "Patient unfit for surgery", "Patient did not attend", "Authorization denied", "Bumped by emergency",
    "Equipment unavailable", "Patient request", "No ICU bed",
  ],
  TEAM_ROLE: [
    "Primary Surgeon", "Secondary Surgeon", "Assistant Surgeon", "Anesthesiologist", "Anesthesia Technician",
    "Scrub Nurse", "Circulating Nurse", "Radiographer", "Perfusionist",
  ],
  IMAGING: ["C-arm fluoroscopy", "Portable chest X-ray", "Portable abdominal X-ray (count discrepancy)", "Intra-op ultrasound", "Intra-op CT", "Angiography", "Specimen radiograph"],
  LAB: ["Arterial blood gas", "Hemoglobin / hematocrit", "Electrolytes", "Blood glucose", "Activated clotting time (ACT)", "PT / INR", "Lactate", "Frozen section"],
  BLOOD: ["Packed red cells", "Fresh frozen plasma", "Platelets", "Cryoprecipitate"],
  DRUG: [
    "Propofol|mg|IV", "Fentanyl|mcg|IV", "Rocuronium|mg|IV", "Sevoflurane|%|Inhaled", "Ondansetron|mg|IV",
    "Dexamethasone|mg|IV", "Cefazolin|g|IV", "Paracetamol|g|IV", "Sugammadex|mg|IV", "Neostigmine|mg|IV",
    "Phenylephrine|mcg|IV", "Ephedrine|mg|IV", "Bupivacaine 0.5% heavy|ml|Intrathecal", "Ketamine|mg|IV",
    "Midazolam|mg|IV", "Tranexamic acid|g|IV", "Heparin|units|IV", "Protamine|mg|IV",
  ],
  CONSENT_KIND: ["SURGERY", "ANESTHESIA", "BLOOD", "IMPLANT", "PHOTOGRAPHY"],
  APPROVAL_KIND: ["PRE_AUTH", "ANESTHESIA_FITNESS", "HIGH_COST_IMPLANT", "HOD_APPROVAL", "ICU_BED"],
};

export type StaffSeed = [code: string, name: string, role: string, specialty: string | null, title: string];
export const STAFF: StaffSeed[] = [
  ["ADM001", "Alex Morgan", "ADMIN", null, "System administrator"],
  ["SUR001", "Dr. Amara Okafor", "SURGEON", "General Surgery", "Consultant surgeon"],
  ["SUR002", "Dr. Rajiv Menon", "SURGEON", "General Surgery", "Consultant, laparoscopic & bariatric"],
  ["SUR003", "Dr. Elena Varga", "SURGEON", "Orthopedics", "Consultant, arthroplasty"],
  ["SUR004", "Dr. Marcus Lindqvist", "SURGEON", "Orthopedics", "Consultant, spine & trauma"],
  ["SUR005", "Dr. Sofia Haddad", "SURGEON", "Cardiothoracic", "Consultant cardiac surgeon"],
  ["SUR006", "Dr. Kenji Watanabe", "SURGEON", "Neurosurgery", "Consultant neurosurgeon"],
  ["SUR007", "Dr. Priya Raman", "SURGEON", "Obstetrics & Gynecology", "Consultant obstetrician"],
  ["SUR008", "Dr. Daniel Mensah", "SURGEON", "Urology", "Consultant urologist"],
  ["SUR009", "Dr. Lucía Fernández", "SURGEON", "ENT", "Consultant ENT surgeon"],
  ["SUR010", "Dr. Hannah Becker", "SURGEON", "Ophthalmology", "Consultant ophthalmologist"],
  ["SUR011", "Dr. Omar Siddiqui", "SURGEON", "Vascular Surgery", "Consultant vascular surgeon"],
  ["SUR012", "Dr. Grace Liu", "SURGEON", "Plastic Surgery", "Consultant plastic surgeon"],
  ["ASU001", "Dr. Tomás Ribeiro", "ASSISTANT_SURGEON", "General Surgery", "Surgical fellow"],
  ["ASU002", "Dr. Aisha Bello", "ASSISTANT_SURGEON", "Orthopedics", "Orthopedic resident"],
  ["ASU003", "Dr. Noah Fischer", "ASSISTANT_SURGEON", "General Surgery", "Surgical resident"],
  ["ANE001", "Dr. Ingrid Solberg", "ANESTHESIOLOGIST", "Anesthesiology", "Consultant anesthesiologist"],
  ["ANE002", "Dr. Vikram Shah", "ANESTHESIOLOGIST", "Anesthesiology", "Consultant, cardiac anesthesia"],
  ["ANE003", "Dr. Chloe Martin", "ANESTHESIOLOGIST", "Anesthesiology", "Consultant, regional anesthesia"],
  ["ANE004", "Dr. Yusuf Demir", "ANESTHESIOLOGIST", "Anesthesiology", "Consultant anesthesiologist"],
  ["ANT001", "Leo Park", "ANESTHESIA_TECH", "Anesthesiology", "Anesthesia technician"],
  ["ANT002", "Mei Tanaka", "ANESTHESIA_TECH", "Anesthesiology", "Anesthesia technician"],
  ["SCN001", "Rosa Delgado", "SCRUB_NURSE", null, "Senior scrub nurse"],
  ["SCN002", "Sam O'Neill", "SCRUB_NURSE", null, "Scrub nurse"],
  ["SCN003", "Fatima Zahra", "SCRUB_NURSE", null, "Scrub nurse"],
  ["SCN004", "Peter Novak", "SCRUB_NURSE", null, "Scrub nurse"],
  ["CIR001", "Julia Costa", "CIRCULATING_NURSE", null, "Circulating nurse"],
  ["CIR002", "Ben Adeyemi", "CIRCULATING_NURSE", null, "Circulating nurse"],
  ["CIR003", "Nina Petrova", "CIRCULATING_NURSE", null, "Circulating nurse"],
  ["CIR004", "Carlos Romero", "CIRCULATING_NURSE", null, "Circulating nurse"],
  ["RAD001", "Arjun Pillai", "RADIOGRAPHER", "Radiology", "Theatre radiographer"],
  ["RAD002", "Emma Walsh", "RADIOGRAPHER", "Radiology", "Theatre radiographer"],
  ["PER001", "Henrik Dahl", "PERFUSIONIST", "Cardiothoracic", "Clinical perfusionist"],
  ["OTC001", "Maya Thompson", "OT_COORDINATOR", null, "Theatre coordinator"],
  ["APR001", "Dr. Robert Hale", "APPROVER", null, "Medical director"],
  ["APR002", "Dr. Lakshmi Iyer", "APPROVER", "General Surgery", "Head of surgery"],
  ["BIL001", "Kevin O'Brien", "BILLING", null, "Surgical coder"],
];

export const THEATRES: [code: string, name: string, kind: string, location: string, specialties: string[]][] = [
  ["OT-01", "Theatre 1", "General", "Main block, level 2", ["General Surgery", "Plastic Surgery", "Vascular Surgery"]],
  ["OT-02", "Theatre 2", "General", "Main block, level 2", ["General Surgery"]],
  ["OT-03", "Theatre 3", "Laminar flow", "Main block, level 2", ["Orthopedics"]],
  ["OT-04", "Hybrid Theatre", "Hybrid", "Cardiac wing, level 3", ["Cardiothoracic", "Vascular Surgery"]],
  ["OT-05", "Theatre 5", "Laminar flow", "Main block, level 3", ["Neurosurgery", "Orthopedics"]],
  ["OT-06", "Women's Theatre", "General", "Maternity wing", ["Obstetrics & Gynecology"]],
  ["OT-07", "Theatre 7", "General", "Main block, level 3", ["Urology", "ENT"]],
  ["OT-08", "Day Surgery 1", "Day care", "Day surgery unit", ["Ophthalmology", "ENT", "Plastic Surgery"]],
];

export const EQUIPMENT: [code: string, name: string, category: string, home: string | null, status: string][] = [
  ["EQ-CARM-1", "C-arm fluoroscopy unit A", "Imaging", "OT-03", "Ready"],
  ["EQ-CARM-2", "C-arm fluoroscopy unit B", "Imaging", "OT-05", "Ready"],
  ["EQ-XR-1", "Portable X-ray", "Imaging", null, "Ready"],
  ["EQ-US-1", "Intra-op ultrasound", "Imaging", null, "Ready"],
  ["EQ-LAP-1", "Laparoscopy tower 4K", "Endoscopy", "OT-02", "Ready"],
  ["EQ-LAP-2", "Laparoscopy tower HD", "Endoscopy", "OT-01", "Ready"],
  ["EQ-ROB-1", "Robotic surgical system", "Robotics", "OT-07", "Ready"],
  ["EQ-MIC-1", "Operating microscope (neuro)", "Optics", "OT-05", "Ready"],
  ["EQ-MIC-2", "Ophthalmic microscope", "Optics", "OT-08", "Ready"],
  ["EQ-LAS-1", "Holmium laser", "Energy", "OT-07", "Ready"],
  ["EQ-PHA-1", "Phacoemulsification system", "Ophthalmic", "OT-08", "Ready"],
  ["EQ-HLM-1", "Heart-lung machine", "Perfusion", "OT-04", "Ready"],
  ["EQ-CS-1", "Cell saver", "Perfusion", "OT-04", "Ready"],
  ["EQ-NAV-1", "Neuro-navigation system", "Navigation", "OT-05", "Maintenance"],
  ["EQ-ART-1", "Arthroscopy tower", "Endoscopy", "OT-03", "Ready"],
  ["EQ-HAR-1", "Ultrasonic energy generator", "Energy", "OT-02", "Ready"],
  ["EQ-VL-1", "Video laryngoscope", "Airway", null, "Ready"],
  ["EQ-WARM-1", "Forced-air patient warmer", "Patient care", null, "Ready"],
];

export type InvSeed = [sku: string, name: string, category: string, uom: string, cost: number, stock: number, reorder: number, vendor: string, implant?: 1, billable?: 0];
export const INVENTORY: InvSeed[] = [
  ["CON-TRO-05", "Trocar 5 mm", "Consumable", "each", 38, 120, 30, "Medline"],
  ["CON-TRO-12", "Trocar 10–12 mm", "Consumable", "each", 64, 80, 25, "Medline"],
  ["CON-VER-01", "Veress needle", "Consumable", "each", 22, 60, 15, "Medline"],
  ["CON-CLIP-01", "Polymer ligating clips (cartridge)", "Consumable", "cartridge", 85, 40, 12, "Teleflex"],
  ["CON-BAG-01", "Endoscopic specimen bag", "Consumable", "each", 41, 50, 15, "Medtronic"],
  ["CON-HAR-01", "Ultrasonic shears 36 cm", "Consumable", "each", 640, 18, 6, "Ethicon"],
  ["CON-ESU-01", "Electrosurgical pencil", "Consumable", "each", 9, 200, 40, "Medtronic"],
  ["CON-SUC-01", "Suction-irrigation set", "Consumable", "each", 27, 70, 20, "Medline"],
  ["CON-GAU-10", "Gauze swabs 10×10 (pack of 10)", "Consumable", "pack", 4, 400, 100, "Medline"],
  ["CON-LAP-05", "Laparotomy sponges (pack of 5)", "Consumable", "pack", 11, 150, 40, "Medline"],
  ["CON-DRP-GEN", "Drape pack, general", "Consumable", "pack", 48, 90, 25, "Mölnlycke"],
  ["CON-DRP-ORT", "Drape pack, extremity", "Consumable", "pack", 62, 40, 15, "Mölnlycke"],
  ["CON-DRP-LAP", "Drape pack, laparoscopy", "Consumable", "pack", 55, 60, 20, "Mölnlycke"],
  ["CON-STA-35", "Skin stapler 35W", "Consumable", "each", 32, 75, 20, "3M"],
  ["CON-FOL-16", "Foley catheter 16 Fr", "Consumable", "each", 6, 140, 30, "Bard"],
  ["CON-DRN-15", "Closed suction drain 15 Fr", "Consumable", "each", 36, 45, 15, "Medtronic"],
  ["CON-CEM-40", "Bone cement 40 g", "Consumable", "pack", 210, 30, 10, "Stryker"],
  ["CON-LAV-01", "Pulsed lavage system", "Consumable", "each", 95, 25, 8, "Zimmer Biomet"],
  ["CON-HEM-01", "Oxidized cellulose hemostat", "Consumable", "each", 58, 4, 10, "Ethicon"],
  ["CON-STP-60", "Linear endostapler 60 mm", "Consumable", "each", 520, 12, 5, "Medtronic"],
  ["CON-RLD-60", "Endostapler reload 60 mm", "Consumable", "each", 230, 30, 10, "Medtronic"],
  ["CON-LSR-365", "Holmium laser fiber 365 µm", "Consumable", "each", 310, 14, 5, "Boston Scientific"],
  ["CON-CHD-28", "Chest drain 28 Fr", "Consumable", "each", 28, 25, 8, "Teleflex"],
  ["SUT-VIC-20", "Absorbable braided suture 2-0", "Suture", "box", 92, 60, 15, "Ethicon"],
  ["SUT-VIC-30", "Absorbable braided suture 3-0", "Suture", "box", 92, 55, 15, "Ethicon"],
  ["SUT-PDS-1L", "Monofilament loop suture 1", "Suture", "box", 140, 30, 10, "Ethicon"],
  ["SUT-PRO-40", "Polypropylene suture 4-0", "Suture", "box", 118, 35, 10, "Ethicon"],
  ["SUT-MON-40", "Monofilament absorbable 4-0", "Suture", "box", 105, 50, 12, "Ethicon"],
  ["SUT-SIL-20", "Silk suture 2-0", "Suture", "box", 54, 3, 8, "Ethicon"],
  ["IMP-MESH-15", "Polypropylene mesh 15×15 cm", "Implant", "each", 260, 22, 6, "Ethicon", 1],
  ["IMP-STN-626", "Ureteral stent 6 Fr 26 cm", "Implant", "each", 145, 28, 8, "Boston Scientific", 1],
  ["IMP-TKA-FEM", "Knee femoral component", "Implant", "each", 2450, 9, 3, "Zimmer Biomet", 1],
  ["IMP-TKA-TIB", "Knee tibial tray", "Implant", "each", 1680, 9, 3, "Zimmer Biomet", 1],
  ["IMP-TKA-PE", "Knee polyethylene insert", "Implant", "each", 720, 11, 3, "Zimmer Biomet", 1],
  ["IMP-THA-CUP", "Hip acetabular cup", "Implant", "each", 1850, 6, 3, "Stryker", 1],
  ["IMP-THA-STM", "Hip femoral stem", "Implant", "each", 2100, 6, 3, "Stryker", 1],
  ["IMP-THA-HD", "Ceramic femoral head 36 mm", "Implant", "each", 980, 2, 3, "Stryker", 1],
  ["IMP-PFN-01", "Proximal femoral nail", "Implant", "each", 1450, 7, 3, "DePuy Synthes", 1],
  ["IMP-VLP-01", "Distal radius volar plate", "Implant", "each", 690, 8, 3, "DePuy Synthes", 1],
  ["IMP-SCR-35", "Locking screw 3.5 mm", "Implant", "each", 85, 120, 30, "DePuy Synthes", 1],
  ["IMP-ACL-SCR", "Interference screw (ACL)", "Implant", "each", 410, 10, 4, "Arthrex", 1],
  ["IMP-PED-01", "Pedicle screw", "Implant", "each", 520, 40, 12, "Medtronic", 1],
  ["IMP-CAGE-C", "Cervical interbody cage", "Implant", "each", 1650, 6, 2, "Medtronic", 1],
  ["IMP-PLT-C", "Anterior cervical plate", "Implant", "each", 1200, 5, 2, "Medtronic", 1],
  ["IMP-PM-DC", "Dual-chamber pacemaker", "Implant", "each", 4800, 4, 2, "Medtronic", 1],
  ["IMP-PM-LD", "Pacing lead", "Implant", "each", 690, 10, 4, "Medtronic", 1],
  ["IMP-AVR-23", "Mechanical aortic valve 23 mm", "Implant", "each", 5200, 3, 1, "Abbott", 1],
  ["IMP-IOL-01", "Monofocal intraocular lens", "Implant", "each", 240, 35, 10, "Alcon", 1],
  ["IMP-VPS-01", "Ventriculoperitoneal shunt kit", "Implant", "each", 1900, 3, 1, "Integra", 1],
  ["IMP-BRI-350", "Breast implant 350 cc", "Implant", "each", 1300, 6, 2, "Mentor", 1],
  ["TRY-LAPMAJ", "Major laparotomy set", "Instrument tray", "set", 0, 6, 2, "CSSD", undefined, 0],
  ["TRY-LAPSC", "Laparoscopy set", "Instrument tray", "set", 0, 8, 2, "CSSD", undefined, 0],
  ["TRY-ORTMAJ", "Major orthopedic set", "Instrument tray", "set", 0, 5, 2, "CSSD", undefined, 0],
  ["TRY-KNEE", "Knee arthroplasty tray", "Instrument tray", "set", 0, 3, 1, "CSSD", undefined, 0],
  ["TRY-HIP", "Hip arthroplasty tray", "Instrument tray", "set", 0, 3, 1, "CSSD", undefined, 0],
  ["TRY-ARTH", "Arthroscopy set", "Instrument tray", "set", 0, 4, 1, "CSSD", undefined, 0],
  ["TRY-SPINE", "Spine set", "Instrument tray", "set", 0, 3, 1, "CSSD", undefined, 0],
  ["TRY-CARD", "Cardiac set", "Instrument tray", "set", 0, 2, 1, "CSSD", undefined, 0],
  ["TRY-CRAN", "Craniotomy set", "Instrument tray", "set", 0, 2, 1, "CSSD", undefined, 0],
  ["TRY-CS", "Caesarean section set", "Instrument tray", "set", 0, 5, 2, "CSSD", undefined, 0],
  ["TRY-EYE", "Cataract set", "Instrument tray", "set", 0, 6, 2, "CSSD", undefined, 0],
  ["TRY-ENT", "ENT set", "Instrument tray", "set", 0, 4, 1, "CSSD", undefined, 0],
  ["TRY-URO", "Cystoscopy / ureteroscopy set", "Instrument tray", "set", 0, 4, 1, "CSSD", undefined, 0],
];

export const DIAGNOSES: [icd: string, desc: string, cat: string][] = [
  ["K80.20", "Calculus of gallbladder without cholecystitis", "Digestive"],
  ["K80.10", "Calculus of gallbladder with chronic cholecystitis", "Digestive"],
  ["K35.80", "Acute appendicitis, unspecified", "Digestive"],
  ["K40.90", "Unilateral inguinal hernia, without obstruction or gangrene", "Digestive"],
  ["K43.9", "Ventral hernia without obstruction or gangrene", "Digestive"],
  ["C18.7", "Malignant neoplasm of sigmoid colon", "Neoplasm"],
  ["C50.911", "Malignant neoplasm of right female breast, unspecified site", "Neoplasm"],
  ["E04.2", "Nontoxic multinodular goiter", "Endocrine"],
  ["E66.01", "Morbid (severe) obesity due to excess calories", "Endocrine"],
  ["M17.11", "Unilateral primary osteoarthritis, right knee", "Musculoskeletal"],
  ["M17.12", "Unilateral primary osteoarthritis, left knee", "Musculoskeletal"],
  ["M16.11", "Unilateral primary osteoarthritis, right hip", "Musculoskeletal"],
  ["S72.001A", "Fracture of neck of right femur, initial encounter", "Injury"],
  ["S52.501A", "Fracture of lower end of right radius, initial encounter", "Injury"],
  ["S83.511A", "Sprain of anterior cruciate ligament of right knee, initial encounter", "Injury"],
  ["S83.241A", "Tear of medial meniscus, right knee, initial encounter", "Injury"],
  ["M48.061", "Spinal stenosis, lumbar region, without neurogenic claudication", "Musculoskeletal"],
  ["M50.20", "Other cervical disc displacement, unspecified level", "Musculoskeletal"],
  ["I25.10", "Atherosclerotic heart disease of native coronary artery", "Circulatory"],
  ["I35.0", "Nonrheumatic aortic valve stenosis", "Circulatory"],
  ["I44.2", "Atrioventricular block, complete", "Circulatory"],
  ["I65.21", "Occlusion and stenosis of right carotid artery", "Circulatory"],
  ["N18.6", "End stage renal disease", "Genitourinary"],
  ["C71.9", "Malignant neoplasm of brain, unspecified", "Neoplasm"],
  ["G91.9", "Hydrocephalus, unspecified", "Nervous system"],
  ["O82", "Encounter for cesarean delivery without indication", "Pregnancy"],
  ["O32.1XX0", "Maternal care for breech presentation", "Pregnancy"],
  ["D25.9", "Leiomyoma of uterus, unspecified", "Genitourinary"],
  ["N83.209", "Unspecified ovarian cyst, unspecified side", "Genitourinary"],
  ["N20.1", "Calculus of ureter", "Genitourinary"],
  ["C61", "Malignant neoplasm of prostate", "Neoplasm"],
  ["N40.1", "Benign prostatic hyperplasia with lower urinary tract symptoms", "Genitourinary"],
  ["J35.01", "Chronic tonsillitis", "Respiratory"],
  ["J34.2", "Deviated nasal septum", "Respiratory"],
  ["J32.9", "Chronic sinusitis, unspecified", "Respiratory"],
  ["H25.9", "Unspecified age-related cataract", "Eye"],
  ["H33.001", "Retinal detachment with retinal break, right eye", "Eye"],
  ["T21.30XA", "Burn of third degree of trunk, initial encounter", "Injury"],
  ["I10", "Essential (primary) hypertension", "Comorbidity"],
  ["E11.9", "Type 2 diabetes mellitus without complications", "Comorbidity"],
  ["J44.9", "Chronic obstructive pulmonary disease, unspecified", "Comorbidity"],
  ["Z79.01", "Long term (current) use of anticoagulants", "Comorbidity"],
];

export type ProcSeed = {
  cpt: string; name: string; specialty: string; opType: string; approach: string;
  dur: number; t: number; wound: string; rvu: number; fee: number;
  addon?: boolean; highRisk?: boolean; implant?: boolean;
  dx: string[]; items: [sku: string, qty: number][]; equipment?: string[]; anesthesia: string; position: string; laterality?: boolean;
};

export const PROCEDURES: ProcSeed[] = [
  // General surgery
  { cpt: "47562", name: "Laparoscopic cholecystectomy", specialty: "General Surgery", opType: "Intermediate", approach: "Laparoscopic", dur: 75, t: 120, wound: "II", rvu: 21.3, fee: 1180, dx: ["K80.20", "K80.10"], items: [["TRY-LAPSC", 1], ["CON-DRP-LAP", 1], ["CON-TRO-05", 3], ["CON-TRO-12", 1], ["CON-CLIP-01", 1], ["CON-BAG-01", 1], ["SUT-VIC-30", 1]], equipment: ["EQ-LAP-1"], anesthesia: "General (ETT)", position: "Reverse Trendelenburg" },
  { cpt: "44970", name: "Laparoscopic appendectomy", specialty: "General Surgery", opType: "Intermediate", approach: "Laparoscopic", dur: 60, t: 90, wound: "III", rvu: 16.5, fee: 920, dx: ["K35.80"], items: [["TRY-LAPSC", 1], ["CON-DRP-LAP", 1], ["CON-TRO-05", 2], ["CON-TRO-12", 1], ["CON-BAG-01", 1], ["SUT-VIC-30", 1]], equipment: ["EQ-LAP-2"], anesthesia: "General (ETT)", position: "Trendelenburg" },
  { cpt: "49505", name: "Open inguinal hernia repair, initial", specialty: "General Surgery", opType: "Intermediate", approach: "Open", dur: 70, t: 120, wound: "I", rvu: 14.9, fee: 860, implant: true, dx: ["K40.90"], items: [["TRY-LAPMAJ", 1], ["CON-DRP-GEN", 1], ["IMP-MESH-15", 1], ["SUT-PRO-40", 1], ["SUT-VIC-30", 1]], anesthesia: "Spinal", position: "Supine", laterality: true },
  { cpt: "49650", name: "Laparoscopic inguinal hernia repair", specialty: "General Surgery", opType: "Intermediate", approach: "Laparoscopic", dur: 80, t: 120, wound: "I", rvu: 13.2, fee: 990, implant: true, dx: ["K40.90"], items: [["TRY-LAPSC", 1], ["CON-DRP-LAP", 1], ["CON-TRO-05", 2], ["CON-TRO-12", 1], ["IMP-MESH-15", 1]], equipment: ["EQ-LAP-1"], anesthesia: "General (ETT)", position: "Trendelenburg", laterality: true },
  { cpt: "49591", name: "Anterior abdominal hernia repair, reducible", specialty: "General Surgery", opType: "Intermediate", approach: "Open", dur: 90, t: 150, wound: "I", rvu: 15.4, fee: 940, implant: true, dx: ["K43.9"], items: [["TRY-LAPMAJ", 1], ["CON-DRP-GEN", 1], ["IMP-MESH-15", 1], ["SUT-PDS-1L", 1]], anesthesia: "General (ETT)", position: "Supine" },
  { cpt: "44204", name: "Laparoscopic partial colectomy with anastomosis", specialty: "General Surgery", opType: "Major", approach: "Laparoscopic", dur: 210, t: 240, wound: "II", rvu: 44.1, fee: 2650, highRisk: true, dx: ["C18.7"], items: [["TRY-LAPSC", 1], ["CON-DRP-LAP", 1], ["CON-TRO-12", 2], ["CON-TRO-05", 2], ["CON-STP-60", 1], ["CON-RLD-60", 2], ["CON-HAR-01", 1], ["CON-DRN-15", 1]], equipment: ["EQ-LAP-1", "EQ-HAR-1"], anesthesia: "General (ETT)", position: "Lithotomy" },
  { cpt: "43775", name: "Laparoscopic sleeve gastrectomy", specialty: "General Surgery", opType: "Major", approach: "Laparoscopic", dur: 120, t: 180, wound: "II", rvu: 34.8, fee: 2100, highRisk: true, dx: ["E66.01"], items: [["TRY-LAPSC", 1], ["CON-DRP-LAP", 1], ["CON-TRO-12", 2], ["CON-TRO-05", 3], ["CON-STP-60", 1], ["CON-RLD-60", 4], ["CON-HAR-01", 1]], equipment: ["EQ-LAP-1", "EQ-HAR-1"], anesthesia: "General (ETT)", position: "Reverse Trendelenburg" },
  { cpt: "60240", name: "Total thyroidectomy", specialty: "General Surgery", opType: "Major", approach: "Open", dur: 150, t: 180, wound: "I", rvu: 30.2, fee: 1750, dx: ["E04.2"], items: [["TRY-LAPMAJ", 1], ["CON-DRP-GEN", 1], ["CON-HAR-01", 1], ["SUT-VIC-30", 1], ["SUT-MON-40", 1]], anesthesia: "General (ETT)", position: "Supine" },
  { cpt: "19301", name: "Partial mastectomy", specialty: "General Surgery", opType: "Intermediate", approach: "Open", dur: 75, t: 120, wound: "I", rvu: 17.6, fee: 1020, dx: ["C50.911"], items: [["TRY-LAPMAJ", 1], ["CON-DRP-GEN", 1], ["SUT-VIC-30", 1], ["SUT-MON-40", 1]], anesthesia: "General (LMA)", position: "Supine", laterality: true },
  { cpt: "38900", name: "Sentinel lymph node mapping (add-on)", specialty: "General Surgery", opType: "Minor", approach: "Open", dur: 20, t: 30, wound: "I", rvu: 4.1, fee: 260, addon: true, dx: ["C50.911"], items: [], anesthesia: "General (LMA)", position: "Supine" },
  { cpt: "44955", name: "Appendectomy at time of other major procedure (add-on)", specialty: "General Surgery", opType: "Minor", approach: "Open", dur: 15, t: 30, wound: "II", rvu: 2.6, fee: 180, addon: true, dx: ["K35.80"], items: [], anesthesia: "General (ETT)", position: "Supine" },
  // Orthopedics
  { cpt: "27447", name: "Total knee arthroplasty", specialty: "Orthopedics", opType: "Major", approach: "Open", dur: 120, t: 150, wound: "I", rvu: 37.5, fee: 2280, implant: true, dx: ["M17.11", "M17.12"], items: [["TRY-KNEE", 1], ["TRY-ORTMAJ", 1], ["CON-DRP-ORT", 1], ["IMP-TKA-FEM", 1], ["IMP-TKA-TIB", 1], ["IMP-TKA-PE", 1], ["CON-CEM-40", 2], ["CON-LAV-01", 1], ["SUT-PDS-1L", 1], ["CON-STA-35", 1]], anesthesia: "Spinal", position: "Supine", laterality: true },
  { cpt: "27130", name: "Total hip arthroplasty", specialty: "Orthopedics", opType: "Major", approach: "Open", dur: 130, t: 180, wound: "I", rvu: 38.4, fee: 2340, implant: true, dx: ["M16.11"], items: [["TRY-HIP", 1], ["TRY-ORTMAJ", 1], ["CON-DRP-ORT", 1], ["IMP-THA-CUP", 1], ["IMP-THA-STM", 1], ["IMP-THA-HD", 1], ["CON-LAV-01", 1], ["SUT-PDS-1L", 1]], anesthesia: "Spinal", position: "Lateral (left)", laterality: true },
  { cpt: "27245", name: "Intramedullary nailing, intertrochanteric femur fracture", specialty: "Orthopedics", opType: "Major", approach: "Open", dur: 95, t: 120, wound: "I", rvu: 33.1, fee: 1890, implant: true, dx: ["S72.001A"], items: [["TRY-ORTMAJ", 1], ["CON-DRP-ORT", 1], ["IMP-PFN-01", 1], ["IMP-SCR-35", 2]], equipment: ["EQ-CARM-1"], anesthesia: "Spinal", position: "Supine", laterality: true },
  { cpt: "25607", name: "ORIF distal radius fracture, extra-articular", specialty: "Orthopedics", opType: "Intermediate", approach: "Open", dur: 75, t: 120, wound: "I", rvu: 18.2, fee: 1080, implant: true, dx: ["S52.501A"], items: [["TRY-ORTMAJ", 1], ["CON-DRP-ORT", 1], ["IMP-VLP-01", 1], ["IMP-SCR-35", 6]], equipment: ["EQ-CARM-1"], anesthesia: "Peripheral nerve block", position: "Supine", laterality: true },
  { cpt: "29881", name: "Knee arthroscopy with meniscectomy", specialty: "Orthopedics", opType: "Day Care", approach: "Arthroscopic", dur: 45, t: 90, wound: "I", rvu: 13.8, fee: 760, dx: ["S83.241A"], items: [["TRY-ARTH", 1], ["CON-DRP-ORT", 1]], equipment: ["EQ-ART-1"], anesthesia: "General (LMA)", position: "Supine", laterality: true },
  { cpt: "29888", name: "Arthroscopic ACL reconstruction", specialty: "Orthopedics", opType: "Major", approach: "Arthroscopic", dur: 100, t: 150, wound: "I", rvu: 22.9, fee: 1450, implant: true, dx: ["S83.511A"], items: [["TRY-ARTH", 1], ["CON-DRP-ORT", 1], ["IMP-ACL-SCR", 2]], equipment: ["EQ-ART-1", "EQ-CARM-1"], anesthesia: "General (LMA)", position: "Supine", laterality: true },
  { cpt: "63047", name: "Lumbar laminectomy with decompression, single level", specialty: "Orthopedics", opType: "Major", approach: "Open", dur: 120, t: 180, wound: "I", rvu: 30.4, fee: 1850, dx: ["M48.061"], items: [["TRY-SPINE", 1], ["CON-DRP-GEN", 1], ["CON-HEM-01", 1], ["CON-DRN-15", 1]], equipment: ["EQ-CARM-2"], anesthesia: "General (ETT)", position: "Prone" },
  { cpt: "22551", name: "Anterior cervical discectomy and fusion, single level", specialty: "Orthopedics", opType: "Major", approach: "Open", dur: 150, t: 180, wound: "I", rvu: 41.2, fee: 2420, implant: true, highRisk: true, dx: ["M50.20"], items: [["TRY-SPINE", 1], ["CON-DRP-GEN", 1], ["IMP-CAGE-C", 1], ["IMP-PLT-C", 1]], equipment: ["EQ-CARM-2", "EQ-MIC-1"], anesthesia: "General (ETT)", position: "Supine" },
  { cpt: "20680", name: "Removal of deep implant", specialty: "Orthopedics", opType: "Minor", approach: "Open", dur: 40, t: 90, wound: "I", rvu: 9.1, fee: 520, dx: ["S52.501A"], items: [["TRY-ORTMAJ", 1]], anesthesia: "General (LMA)", position: "Supine", laterality: true },
  // Cardiothoracic
  { cpt: "33533", name: "Coronary artery bypass, single arterial graft", specialty: "Cardiothoracic", opType: "Major", approach: "Open", dur: 270, t: 300, wound: "I", rvu: 61.5, fee: 3850, highRisk: true, dx: ["I25.10"], items: [["TRY-CARD", 1], ["CON-DRP-GEN", 1], ["CON-CHD-28", 2], ["SUT-PRO-40", 3], ["CON-HEM-01", 2]], equipment: ["EQ-HLM-1", "EQ-CS-1"], anesthesia: "General (ETT)", position: "Supine" },
  { cpt: "33405", name: "Aortic valve replacement with prosthetic valve", specialty: "Cardiothoracic", opType: "Major", approach: "Open", dur: 240, t: 300, wound: "I", rvu: 66.8, fee: 4120, highRisk: true, implant: true, dx: ["I35.0"], items: [["TRY-CARD", 1], ["CON-DRP-GEN", 1], ["IMP-AVR-23", 1], ["CON-CHD-28", 2], ["SUT-PRO-40", 4]], equipment: ["EQ-HLM-1", "EQ-CS-1"], anesthesia: "General (ETT)", position: "Supine" },
  { cpt: "33208", name: "Insertion of dual-chamber pacemaker", specialty: "Cardiothoracic", opType: "Intermediate", approach: "Percutaneous", dur: 75, t: 120, wound: "I", rvu: 15.1, fee: 980, implant: true, dx: ["I44.2"], items: [["CON-DRP-GEN", 1], ["IMP-PM-DC", 1], ["IMP-PM-LD", 2], ["SUT-SIL-20", 1]], equipment: ["EQ-CARM-2"], anesthesia: "Monitored anesthesia care", position: "Supine" },
  // Vascular
  { cpt: "35301", name: "Carotid endarterectomy", specialty: "Vascular Surgery", opType: "Major", approach: "Open", dur: 135, t: 180, wound: "I", rvu: 33.6, fee: 2050, highRisk: true, dx: ["I65.21"], items: [["CON-DRP-GEN", 1], ["SUT-PRO-40", 2]], anesthesia: "General (ETT)", position: "Supine", laterality: true },
  { cpt: "36821", name: "Arteriovenous fistula creation", specialty: "Vascular Surgery", opType: "Intermediate", approach: "Open", dur: 80, t: 120, wound: "I", rvu: 14.2, fee: 880, dx: ["N18.6"], items: [["CON-DRP-ORT", 1], ["SUT-PRO-40", 1]], anesthesia: "Peripheral nerve block", position: "Supine", laterality: true },
  // Neurosurgery
  { cpt: "61510", name: "Craniotomy for excision of supratentorial tumor", specialty: "Neurosurgery", opType: "Major", approach: "Microscopic", dur: 300, t: 360, wound: "I", rvu: 68.4, fee: 4300, highRisk: true, dx: ["C71.9"], items: [["TRY-CRAN", 1], ["CON-DRP-GEN", 1], ["CON-HEM-01", 2], ["SUT-VIC-30", 2]], equipment: ["EQ-MIC-1", "EQ-NAV-1"], anesthesia: "General (ETT)", position: "Supine" },
  { cpt: "62223", name: "Ventriculoperitoneal shunt placement", specialty: "Neurosurgery", opType: "Major", approach: "Open", dur: 90, t: 120, wound: "I", rvu: 29.8, fee: 1780, implant: true, dx: ["G91.9"], items: [["TRY-CRAN", 1], ["CON-DRP-GEN", 1], ["IMP-VPS-01", 1]], anesthesia: "General (ETT)", position: "Supine" },
  // OBGYN
  { cpt: "59514", name: "Cesarean delivery only", specialty: "Obstetrics & Gynecology", opType: "Major", approach: "Open", dur: 55, t: 90, wound: "II", rvu: 20.3, fee: 1240, dx: ["O82", "O32.1XX0"], items: [["TRY-CS", 1], ["CON-DRP-GEN", 1], ["SUT-VIC-20", 2], ["CON-FOL-16", 1]], anesthesia: "Spinal", position: "Supine" },
  { cpt: "58150", name: "Total abdominal hysterectomy", specialty: "Obstetrics & Gynecology", opType: "Major", approach: "Open", dur: 120, t: 180, wound: "II", rvu: 29.4, fee: 1720, dx: ["D25.9"], items: [["TRY-LAPMAJ", 1], ["CON-DRP-GEN", 1], ["SUT-VIC-20", 2], ["CON-FOL-16", 1]], anesthesia: "General (ETT)", position: "Supine" },
  { cpt: "58571", name: "Laparoscopic total hysterectomy with salpingo-oophorectomy", specialty: "Obstetrics & Gynecology", opType: "Major", approach: "Laparoscopic", dur: 140, t: 180, wound: "II", rvu: 30.8, fee: 1880, dx: ["D25.9"], items: [["TRY-LAPSC", 1], ["CON-DRP-LAP", 1], ["CON-TRO-12", 1], ["CON-TRO-05", 3], ["CON-HAR-01", 1], ["CON-FOL-16", 1]], equipment: ["EQ-LAP-2"], anesthesia: "General (ETT)", position: "Lithotomy" },
  { cpt: "58661", name: "Laparoscopic removal of adnexal structures", specialty: "Obstetrics & Gynecology", opType: "Intermediate", approach: "Laparoscopic", dur: 70, t: 120, wound: "II", rvu: 17.4, fee: 1010, dx: ["N83.209"], items: [["TRY-LAPSC", 1], ["CON-DRP-LAP", 1], ["CON-TRO-05", 2], ["CON-BAG-01", 1]], equipment: ["EQ-LAP-2"], anesthesia: "General (ETT)", position: "Lithotomy" },
  // Urology
  { cpt: "52356", name: "Ureteroscopy with laser lithotripsy and stent", specialty: "Urology", opType: "Day Care", approach: "Endoscopic", dur: 60, t: 120, wound: "II", rvu: 16.8, fee: 980, implant: true, dx: ["N20.1"], items: [["TRY-URO", 1], ["CON-DRP-GEN", 1], ["CON-LSR-365", 1], ["IMP-STN-626", 1]], equipment: ["EQ-LAS-1", "EQ-CARM-2"], anesthesia: "General (LMA)", position: "Lithotomy", laterality: true },
  { cpt: "55866", name: "Robotic-assisted radical prostatectomy", specialty: "Urology", opType: "Major", approach: "Robotic-assisted", dur: 210, t: 300, wound: "II", rvu: 52.2, fee: 3250, highRisk: true, dx: ["C61"], items: [["TRY-LAPSC", 1], ["CON-DRP-LAP", 1], ["CON-TRO-12", 2], ["CON-CLIP-01", 1], ["CON-FOL-16", 1], ["CON-DRN-15", 1]], equipment: ["EQ-ROB-1"], anesthesia: "General (ETT)", position: "Trendelenburg" },
  { cpt: "52601", name: "Transurethral resection of prostate", specialty: "Urology", opType: "Intermediate", approach: "Endoscopic", dur: 75, t: 120, wound: "II", rvu: 20.1, fee: 1150, dx: ["N40.1"], items: [["TRY-URO", 1], ["CON-DRP-GEN", 1], ["CON-FOL-16", 1]], anesthesia: "Spinal", position: "Lithotomy" },
  // ENT
  { cpt: "42826", name: "Tonsillectomy, age 12 or over", specialty: "ENT", opType: "Day Care", approach: "Open", dur: 40, t: 60, wound: "II", rvu: 7.6, fee: 520, dx: ["J35.01"], items: [["TRY-ENT", 1], ["CON-DRP-GEN", 1]], anesthesia: "General (ETT)", position: "Supine" },
  { cpt: "30520", name: "Septoplasty", specialty: "ENT", opType: "Day Care", approach: "Endoscopic", dur: 60, t: 90, wound: "II", rvu: 11.5, fee: 690, dx: ["J34.2"], items: [["TRY-ENT", 1], ["CON-DRP-GEN", 1]], anesthesia: "General (ETT)", position: "Supine" },
  { cpt: "31255", name: "Endoscopic sinus surgery, total ethmoidectomy", specialty: "ENT", opType: "Intermediate", approach: "Endoscopic", dur: 90, t: 120, wound: "II", rvu: 14.8, fee: 940, dx: ["J32.9"], items: [["TRY-ENT", 1], ["CON-DRP-GEN", 1]], anesthesia: "General (ETT)", position: "Supine", laterality: true },
  // Ophthalmology
  { cpt: "66984", name: "Cataract extraction with intraocular lens", specialty: "Ophthalmology", opType: "Day Care", approach: "Microscopic", dur: 30, t: 45, wound: "I", rvu: 10.2, fee: 640, implant: true, dx: ["H25.9"], items: [["TRY-EYE", 1], ["IMP-IOL-01", 1]], equipment: ["EQ-PHA-1", "EQ-MIC-2"], anesthesia: "Local", position: "Supine", laterality: true },
  { cpt: "67108", name: "Repair of retinal detachment with vitrectomy", specialty: "Ophthalmology", opType: "Intermediate", approach: "Microscopic", dur: 90, t: 120, wound: "I", rvu: 26.4, fee: 1560, dx: ["H33.001"], items: [["TRY-EYE", 1]], equipment: ["EQ-MIC-2"], anesthesia: "Peripheral nerve block", position: "Supine", laterality: true },
  // Plastic
  { cpt: "15100", name: "Split-thickness skin graft, trunk, first 100 cm²", specialty: "Plastic Surgery", opType: "Intermediate", approach: "Open", dur: 70, t: 120, wound: "III", rvu: 16.2, fee: 940, dx: ["T21.30XA"], items: [["CON-DRP-GEN", 1], ["CON-STA-35", 1]], anesthesia: "General (ETT)", position: "Supine" },
  { cpt: "19325", name: "Breast augmentation with implant", specialty: "Plastic Surgery", opType: "Intermediate", approach: "Open", dur: 90, t: 120, wound: "I", rvu: 15.0, fee: 1200, implant: true, dx: ["C50.911"], items: [["CON-DRP-GEN", 1], ["IMP-BRI-350", 2], ["SUT-MON-40", 1]], anesthesia: "General (LMA)", position: "Supine", laterality: true },
  // Anesthesia / support add-ons
  { cpt: "64447", name: "Femoral nerve block, single injection", specialty: "Anesthesiology", opType: "Minor", approach: "Percutaneous", dur: 15, t: 30, wound: "I", rvu: 2.4, fee: 160, addon: true, dx: ["M17.11", "M17.12", "S72.001A"], items: [], equipment: ["EQ-US-1"], anesthesia: "Peripheral nerve block", position: "Supine", laterality: true },
  { cpt: "36556", name: "Central venous catheter insertion, age 5+", specialty: "Anesthesiology", opType: "Minor", approach: "Percutaneous", dur: 15, t: 30, wound: "I", rvu: 3.3, fee: 210, addon: true, dx: [], items: [], equipment: ["EQ-US-1"], anesthesia: "General (ETT)", position: "Supine" },
];

/** Secondary procedures commonly paired with a primary CPT. */
export const SECONDARY_FOR: Record<string, string[]> = {
  "27447": ["64447"],
  "27245": ["64447"],
  "19301": ["38900"],
  "44204": ["44955"],
  "33533": ["36556"],
  "33405": ["36556"],
  "61510": ["36556"],
  "58150": ["58661"],
};

export const FIRST_NAMES = ["Liam", "Olivia", "Noah", "Emma", "Mateo", "Ava", "Arjun", "Zara", "Ethan", "Mia", "Lucas", "Isla", "Hiro", "Amelia", "Kwame", "Sofia", "Ibrahim", "Chloe", "Diego", "Leila", "Samuel", "Grace", "Ravi", "Hana", "Jonah", "Maya", "Felix", "Nadia", "Oscar", "Elif", "Tariq", "Ruth", "Andrei", "Keira", "Malik", "Ines", "Theo", "Yara", "George", "Anya"];
export const LAST_NAMES = ["Johnson", "Silva", "Nguyen", "Patel", "Kowalski", "Mensah", "Garcia", "Kim", "Murphy", "Rossi", "Haddad", "Okoro", "Andersen", "Chen", "Dubois", "Kaur", "Schmidt", "Ali", "Brennan", "Yilmaz", "Costa", "Ivanova", "Moreau", "Tanaka", "Osei", "Hughes", "Novak", "Rahman", "Lopez", "Sato"];
export const INSURERS = ["BlueCross Plus", "Meridian Health", "Unity Care", "National Health Fund", null];
export const ALLERGIES = ["NKDA", "NKDA", "NKDA", "Penicillin", "Latex", "Sulfa drugs", "Iodinated contrast", "NKDA", "Morphine"];
export const COMORBIDITIES = ["", "", "Hypertension", "Type 2 diabetes", "Hypertension, type 2 diabetes", "COPD", "Atrial fibrillation on anticoagulation", "Obesity", "Asthma", "Chronic kidney disease stage 3"];
