/**
 * One-time mechanical import of the AllyVora Quality SOURCE frontend.
 *
 *   node scripts/quality/import.mjs [--force]
 *
 * Source: reference/frontend/allyvora-quality/allyvora-quality/web/src (read only; override with QUALITY_REFERENCE_ROOT).
 * Copies the thirteen static pages, the two dynamic detail pages (indicators/[id], reports/[id]) and the
 * shared components into packages/reference-quality/src, applying only mechanical rewrites:
 *   - "@/..." aliases become relative paths
 *   - next/link -> ReferenceLink, next/navigation -> src/lib/navigation (host path/router)
 *   - promise route params (`use(params)`) become plain params from the module's route resolver
 *   - native button/input/textarea/select/table elements -> shared Source controls and Table adapters (src/components/controls)
 *   - fmt* helpers -> the host-formatted useQualityFormat() hook, injected into each component that calls them
 * Not copied: the standalone shell (layout, Sidebar, Header, Logo, nav), the login page, global CSS (generated by
 * scripts/quality/styles.mjs) and lib/api|auth|hooks (hand adapted onto the host transport).
 * Existing files are kept unless --force is given, so later hand adaptation is never overwritten.
 */
import {existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync} from 'node:fs';
import {dirname, join, relative, resolve} from 'node:path';
import ts from 'typescript';

const root = resolve(import.meta.dirname, '../..');
const source = process.env.QUALITY_REFERENCE_ROOT ?? '/home/pepadmin/pb/saas/reference/frontend/allyvora-quality/allyvora-quality/web/src';
const target = join(root, 'packages/reference-quality/src');
const force = process.argv.includes('--force');
const walk = dir => readdirSync(dir, {withFileTypes: true}).flatMap(e => e.isDirectory() ? walk(join(dir, e.name)) : [join(dir, e.name)]);
const rel = (from, to) => { const v = relative(dirname(from), to).split('\\').join('/'); return v.startsWith('.') ? v : './' + v; };
const API = ['api', 'download'];
const FMT = ['fmtNumber', 'fmtValue', 'fmtMinutes', 'fmtPeriod', 'fmtPeriodRange', 'fmtDateTime', 'fmtDate', 'fmtTime', 'fmtRelative'];
const CONTROLS = {button: 'SourceButton', input: 'SourceInput', textarea: 'SourceTextarea', select: 'SourceSelect', table: 'Table', thead: 'TableHeader', tbody: 'TableBody', tr: 'TableRow', th: 'TableHead', td: 'TableCell'};

const files = [
  ...walk(join(source, 'app/(app)')).filter(f => f.endsWith('/page.tsx')),
  ...['ResultDrawer', 'TransactionDrawer', 'ReportRenderer', 'IndicatorForm', 'kpi', 'ui', 'PeriodPicker', 'charts', 'toast'].map(n => join(source, 'components', n + '.tsx')),
  join(source, 'lib/types.ts'),
];

/** Inject `const {...} = useQualityFormat()` / `useQualityApi()` at the top of each component that calls them. */
function injectHooks(text, dest) {
  const sf = ts.createSourceFile(dest, text, ts.ScriptTarget.Latest, true, ts.ScriptKind.TSX);
  const edits = []; const orphans = [];
  const callsIn = (node, names) => { const found = new Set(); const v = n => { if (ts.isIdentifier(n) && names.includes(n.text) && !ts.isImportSpecifier(n.parent) && !(ts.isPropertyAccessExpression(n.parent) && n.parent.name === n) && !(ts.isPropertyAssignment(n.parent) && n.parent.name === n)) found.add(n.text); ts.forEachChild(n, v); }; v(node); return found; };
  for (const st of sf.statements) {
    let name, body;
    if (ts.isFunctionDeclaration(st) && st.name && st.body) { name = st.name.text; body = st.body; }
    else if (ts.isVariableStatement(st)) { const d = st.declarationList.declarations[0]; if (d?.initializer && (ts.isArrowFunction(d.initializer) || ts.isFunctionExpression(d.initializer)) && ts.isBlock(d.initializer.body)) { name = d.name.getText(sf); body = d.initializer.body; } else if (d?.initializer && ts.isArrowFunction(d.initializer)) { name = d.name.getText(sf); const f = [...callsIn(d.initializer, [...FMT, ...API])]; if (f.length) orphans.push(`${name}: expression-bodied uses ${f.join(',')}`); } }
    if (!body) continue;
    const fmt = callsIn(body, FMT), api = callsIn(body, API);
    if (!fmt.size && !api.size) continue;
    if (!/^[A-Z]/.test(name)) { orphans.push(`${name}: non-component uses ${[...fmt, ...api].join(',')}`); continue; }
    let lines = '';
    if (api.size) lines += `\n  const { ${[...api].sort().join(', ')} } = useQualityApi();`;
    if (fmt.size) lines += `\n  const { ${[...fmt].sort().join(', ')} } = useQualityFormat();`;
    edits.push({at: body.getStart(sf) + 1, text: lines});
  }
  for (const e of edits.sort((a, b) => b.at - a.at)) text = text.slice(0, e.at) + e.text + text.slice(e.at);
  return {text, orphans};
}

function rewrite(text, dest) {
  // Alias imports -> relative.
  text = text.replace(/from "@\/([^"]+)"/g, (_m, p) => `from "${rel(dest, join(target, p))}"`);
  // fmt* leave the lib/format import; the hook replaces them.
  let orphans = [];
  if (/\.tsx$/.test(dest)) {
    text = text.replace(/import \{([^}]+)\} from "(\.[^"]*\/lib\/format)";/, (m, names, path) => {
      const keep = names.split(',').map(s => s.trim()).filter(n => n && !FMT.includes(n));
      const hook = names.split(',').some(n => FMT.includes(n.trim()));
      return [keep.length ? `import { ${keep.join(', ')} } from "${path}";` : '', hook ? `import { useQualityFormat } from "${path}";` : ''].filter(Boolean).join('\n');
    });
    text = text.replace(/import \{([^}]+)\} from "(\.[^"]*\/lib\/api)";/, (m, names, path) => {
      const keep = names.split(',').map(s => s.trim()).filter(n => n && !API.includes(n));
      const hook = names.split(',').some(n => API.includes(n.trim()));
      return [keep.length ? `import { ${keep.join(', ')} } from "${path}";` : '', hook ? `import { useQualityApi } from "${path}";` : ''].filter(Boolean).join('\n');
    });
  }
  text = text.replace(/import Link from "next\/link";/, 'import { ReferenceLink as Link } from "@pepbits/reference-host";');
  text = text.replace(/from "next\/navigation"/, `from "${rel(dest, join(target, 'lib/navigation'))}"`);
  text = text.replace(/params: Promise<\{ id: string \}>/, 'params: { id: string }').replace(/= use\(params\)/, '= params').replace(/import \{ use, /, 'import { ');
  if (/\.tsx$/.test(dest)) {
    if (!/components\/ui\.tsx$/.test(dest) || true) {
      const used = [];
      for (const [tag, name] of Object.entries(CONTROLS)) {
        const open = new RegExp(`<(/?)${tag}(?=[\\s>/])`, 'g');
        if (open.test(text)) { text = text.replace(open, `<$1${name}`); used.push(name); }
      }
      if (used.length) {
        const lines = text.split('\n'), at = lines.findIndex(l => /^"use client";?$/.test(l)) + 1;
        lines.splice(at, 0, `import { ${used.join(', ')} } from "${rel(dest, join(target, 'components/controls'))}";`);
        text = lines.join('\n');
      }
    }
    const r = injectHooks(text, dest); text = r.text; orphans = r.orphans;
  }
  return {text, orphans};
}

for (const file of files) {
  const relPath = relative(source, file);
  const dest = join(target, relPath);
  if (existsSync(dest) && !force) { console.log('keep   ', relative(root, dest)); continue; }
  const {text, orphans} = rewrite(readFileSync(file, 'utf8'), dest);
  mkdirSync(dirname(dest), {recursive: true});
  writeFileSync(dest, text);
  console.log('write  ', relative(root, dest), orphans.length ? '\n   NEEDS HAND FIX: ' + orphans.join('; ') : '');
}
