import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync} from 'node:fs';
import {REFERENCE_MODULES,referenceNavigationTarget} from '../packages/erp-config/src/reference-modules.ts';
import {loadPlaywright,BASE,API} from './harness.mjs';

// Authenticated dummy API/browser acceptance. No browser API interception or fabricated UI actors.
const output=process.env.E2E_ARTIFACTS??'/tmp/healthcare-suite-browser';mkdirSync(output,{recursive:true});
const args=process.env.E2E_DNS_OVERRIDE?[`--host-resolver-rules=${process.env.E2E_DNS_OVERRIDE}`]:[];
const browser=await loadPlaywright().chromium.launch({chromiumSandbox:false,args});
const moduleId='reference-healthcare-suite',results=[],errors=[],mutations=[],networkFailures=[],consoleErrors=[];const flowOnly=process.env.E2E_HEALTHCARE_SUITE_FLOW_ONLY==='1';let activePage;
const catalog=REFERENCE_MODULES.find(module=>module.id===moduleId);assert.equal(catalog.pages.length,32);
const root=page=>page.locator('[data-reference-module="healthcare-suite"]');
const record=(name,detail={})=>{results.push({name,status:'passed',...detail});writeFileSync(`${output}/progress.json`,JSON.stringify({completed:results.length,last:name})+'\n');console.log('PASS '+name);};
async function login(username){
 const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();page.setDefaultTimeout(30000);activePage=page;page.on('pageerror',error=>errors.push(error.message));page.on('console',message=>{if(message.type()==='error')consoleErrors.push({text:message.text(),location:message.location()});});page.on('requestfailed',request=>networkFailures.push({url:request.url(),failure:request.failure()?.errorText}));page.on('response',response=>{if(response.status()>=400)networkFailures.push({url:response.url(),status:response.status()});});
 await page.goto(BASE,{waitUntil:'domcontentloaded'});await page.locator('input').first().fill(username);await page.locator('input[type=password]').fill(username);await page.locator('button[type=submit]').click();await page.locator('header [data-tour=module]').waitFor();return{context,page};
}
function href(path){const target=referenceNavigationTarget(moduleId,path);return `${BASE}/${moduleId}/${target.pageId}/${encodeURIComponent(target.recordId)}`;}
async function ready(page){await root(page).waitFor();await page.waitForFunction(()=>{const node=document.querySelector('[data-reference-module="healthcare-suite"]');return node&&node.innerText.length>70&&!/\bLoading(?:\s|…)/i.test(node.innerText)&&!node.querySelector('[aria-busy="true"],.animate-spin');});return root(page);}
async function go(page,path){await page.goto(href(path),{waitUntil:'domcontentloaded'});return ready(page);}
async function api(page,path,opts={}){const token=await page.evaluate(()=>localStorage.getItem('nexora-session-token'));const response=await fetch(`${API}/reference-modules/healthcare-suite/api${path}`,{method:opts.method??'GET',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json','X-Product-Id':'nexora','X-Reference-Branch':opts.branch??(opts.username==='user1'?'dubai':'hq'),'X-Reference-Facility':opts.facility??'F001',...opts.headers},...(opts.body===undefined?{}:{body:JSON.stringify(opts.body)})});return{status:response.status,body:await response.json()};}
function post(page,path){return page.waitForResponse(response=>new URL(response.url()).pathname.endsWith('/healthcare-suite/api'+path)&&response.request().method()==='POST');}
async function command(page,path,click){const pending=post(page,path).then(response=>({response}),error=>({error}));await click();const settled=await pending;if(settled.error)throw settled.error;const response=settled.response;const body=await response.json();mutations.push({path,status:response.status(),hasOperationId:!!response.request().headers()['idempotency-key']});assert.equal(response.status(),201,JSON.stringify(body));return body;}
try{
 const {context,page}=await login('admin');activePage=page;
 await page.locator('header [data-tour=module] button').click();const choices=page.getByRole('listbox');await choices.waitFor();await choices.getByRole('option',{name:/Healthcare Suite/}).click();await ready(page);assert.ok(new URL(page.url()).pathname.startsWith('/'+moduleId+'/'));record('authenticated header module selection');await page.screenshot({path:`${output}/header-dashboard.png`});
 const session=await api(page,'/session');assert.equal(session.status,200);assert.equal(session.body.user.id,'USR-00301');assert.equal(session.body.user.role,'enterprise-admin');record('actual host actor session');
 for(const destination of flowOnly?[]:catalog.pages){
  const failures=[],watch=response=>{if(response.url().includes('/reference-modules/healthcare-suite/')&&response.status()>=400)failures.push({url:response.url(),status:response.status()});};page.on('response',watch);
  await page.goto(`${BASE}/${moduleId}/${destination.id}`,{waitUntil:'domcontentloaded'});const moduleRoot=await ready(page);const text=await moduleRoot.innerText();assert.ok(text.length>70,destination.id);assert.ok(!/Healthcare Suite page not found|Some fields need attention|Invalid lookup response|Something went wrong on the server/.test(text),destination.id);assert.deepEqual(failures,[],destination.id);page.off('response',watch);await moduleRoot.screenshot({path:`${output}/${destination.id}.png`});record('static '+destination.path,{pageId:destination.id});
 }
 for(const path of flowOnly?[]:['/masters/payers/new','/masters/providers/P001','/patients/PT00001','/patients/new','/encounters/new']){await go(page,path);await root(page).screenshot({path:`${output}/dynamic-${path.replace(/[^a-zA-Z0-9]+/g,'-')}.png`});record('dynamic '+path);}
 await go(page,'/patients/new');
 const firstName='Browser'+Date.now().toString(36),lastName='Synthetic';
 await root(page).locator('#pt-firstName').fill(firstName);await root(page).locator('#pt-lastName').fill(lastName);await root(page).getByLabel(/Gender/).selectOption('Female');await root(page).locator('#pt-phone').fill('+971 50 888 7654');
 const patient=await command(page,'/patients',()=>root(page).getByRole('button',{name:'Save',exact:true}).click());await ready(page);assert.match(patient.mrn,/^MRN\d+/);await root(page).getByText(patient.mrn,{exact:false}).first().waitFor();assert.equal((await api(page,`/patients/${patient.id}`)).body.firstName,firstName);record('UI patient registration and persisted API record',{patientId:patient.id});await root(page).screenshot({path:`${output}/created-patient.png`});
 const day=new Date(Date.now()+86400000).toISOString().slice(0,10);await go(page,`/appointments?date=${day}&patientId=${patient.id}&resourceId=R001`);await root(page).getByText(`${firstName} ${lastName}`,{exact:false}).first().waitFor();await root(page).getByRole('button',{name:/^Book Dr\. Sara Haddad at /}).first().click();const appointment=await command(page,'/appointments',()=>root(page).getByRole('button',{name:/^Book \d/}).click());assert.equal(appointment.patientId,patient.id);assert.equal(appointment.createdBy,session.body.user.id);await root(page).getByRole('button',{name:'Check in & create encounter',exact:true}).waitFor();record('UI appointment books a source provider slot',{appointmentId:appointment.id,date:day});await root(page).screenshot({path:`${output}/created-appointment.png`});
 await root(page).getByRole('button',{name:'Check in & create encounter',exact:true}).click();await ready(page);await root(page).getByRole('button',{name:/Create outpatient encounter/i}).waitFor();const encounter=await command(page,'/encounters',()=>root(page).getByRole('button',{name:/Create outpatient encounter/i}).click());await ready(page);assert.equal(encounter.appointment.id,appointment.id);assert.equal(encounter.createdBy,session.body.user.id);assert.equal((await api(page,`/appointments/${appointment.id}`)).body.status,'Arrived');record('UI check-in creates linked encounter and consultation charge',{encounterId:encounter.id});
 const search=root(page).getByPlaceholder('Order a service, drug or consumable: name, code or category');await search.fill('Complete blood count');const order=await command(page,`/encounters/${encounter.id}/orders`,()=>root(page).getByRole('option',{name:/Complete blood count/i}).click());assert.equal(order.status,'Draft');await root(page).getByRole('button',{name:'Sign 1',exact:true}).waitFor();await command(page,`/encounters/${encounter.id}/orders/sign`,()=>root(page).getByRole('button',{name:'Sign 1',exact:true}).click());const signed=(await api(page,`/encounters/${encounter.id}`)).body.orders.find(line=>line.id===order.id);assert.equal(signed.status,'Signed');record('UI catalog order and signing');await root(page).screenshot({path:`${output}/signed-encounter.png`});
 await go(page,`/billing/hospital?encounterId=${encounter.id}`);await root(page).getByRole('button',{name:/Invoice & collect/}).waitFor();const invoice=await command(page,'/billing/invoices',()=>root(page).getByRole('button',{name:/Invoice & collect/}).click());const dialog=page.getByRole('dialog');await dialog.waitFor();assert.equal(invoice.status,'Paid');assert.equal(invoice.balance,0);assert.equal(invoice.createdBy,session.body.user.id);assert.equal(invoice.lines.length,2);assert.equal((await api(page,`/billing/invoices/${invoice.id}`)).body.paid,invoice.patientShare);await dialog.screenshot({path:`${output}/paid-invoice.png`});record('UI hospital invoice, collection and printable invoice',{invoiceId:invoice.id});await dialog.getByRole('button',{name:'Open in invoices',exact:true}).click();await ready(page);const invoicePane=root(page).locator('aside');await invoicePane.getByText(invoice.invoiceNo,{exact:true}).waitFor();assert.ok(decodeURIComponent(new URL(page.url()).pathname).includes('/billing/invoices?open='+invoice.id));await invoicePane.screenshot({path:`${output}/selected-invoice.png`});record('dynamic invoice URL opens created invoice');
 await go(page,'/encounters/new?patientId='+patient.id);await root(page).getByLabel('Healthcare Suite facility',{exact:true}).selectOption('F002');await root(page).getByRole('button',{name:/Create pharmacy encounter/i}).waitFor();record('selected source pharmacy facility controls new encounter type');
 const finance=await login('user1');await go(finance.page,'/patients');const readonlySession=await api(finance.page,'/session',{username:'user1'});assert.equal(readonlySession.status,200);assert.equal(readonlySession.body.canWrite,false);assert.equal((await api(finance.page,'/patients',{username:'user1',method:'POST',body:{firstName:'Blocked'}})).status,403);record('finance role reads authenticated module and API rejects writes');await finance.context.close();
 const student=await login('school-student');await student.page.goto(`${BASE}/${moduleId}/reference-healthcare-suite-dashboard`,{waitUntil:'domcontentloaded'});await student.page.getByText(/^(?:Page unavailable for your role|This page is not configured)$/).waitFor();assert.equal(await root(student.page).count(),0);assert.equal((await api(student.page,'/session')).status,403);record('School-only actor cannot open Healthcare Suite');await student.context.close();
 assert.ok(mutations.every(mutation=>mutation.hasOperationId),'every consequential UI POST carries an operation identifier');assert.deepEqual(errors,[]);record('mutation identities and no browser page errors');await context.close();
}catch(error){errors.push(error.stack??error.message);if(activePage){await activePage.screenshot({path:`${output}/failure.png`}).catch(()=>{});writeFileSync(`${output}/failure-visible-text.txt`,await activePage.locator('body').innerText().catch(()=>''));}throw error;}finally{writeFileSync(`${output}/results.json`,JSON.stringify({base:BASE,api:API,scope:flowOnly?'workflow-only':'full',results,errors,mutations,networkFailures,consoleErrors},null,2)+'\n');await browser.close();}
