import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {loadPlaywright} from './harness.mjs';
import {audit} from './a11y.mjs';
import {NEXORA_PRODUCT,PAGE_TEMPLATES} from '../packages/erp-config/src/index.ts';
// The library lists every registered template the product installs; the catalog grows over time.
const EXPECTED_TEMPLATES=PAGE_TEMPLATES.filter(item=>NEXORA_PRODUCT.pages[item.id]).length;
const browser=await loadPlaywright().chromium.launch({chromiumSandbox:false});
try {
 const context=await browser.newContext({viewport:{width:1800,height:1150}}),page=await context.newPage();page.setDefaultTimeout(30000);
 const errors:string[]=[],writes:string[]=[];page.on('pageerror',error=>errors.push(error.message));
 const preferences:Record<string,unknown>={sidebarPinned:true,reducedMotion:true,floatingWindows:false,formNavigation:'tabs'};
 await context.route('**/preferences',async route=>{if(route.request().method()==='PUT')Object.assign(preferences,route.request().postDataJSON().preferences??route.request().postDataJSON());await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({preferences})});});
 await page.goto(process.env.E2E_DESKTOP??'http://127.0.0.1:3109');await page.getByPlaceholder('user1').fill('admin');await page.locator('input[type=password]').fill('admin');await page.locator('button[type=submit]').click();await page.locator('header').first().waitFor();
 page.on('request',request=>{if(['POST','PUT','PATCH','DELETE'].includes(request.method())&&/\/(records|drafts|imports|approvals|record-panels)(\/|$)/.test(new URL(request.url()).pathname))writes.push(request.url());});
 async function open(id:string){if(await page.getByRole('tab').count()>=10){await page.getByRole('button',{name:'Tab options',exact:true}).click();await page.getByRole('button',{name:'Close other tabs',exact:true}).click();}await page.keyboard.press('Control+k');const dialog=page.getByRole('dialog');await dialog.locator('input').first().fill(id);await dialog.locator('button.group').first().click();await page.locator(`[data-template-library="${id}"]`).waitFor();}
 await open('page-templates');let root=page.locator('[data-template-library="page-templates"]');assert.equal(await root.getByRole('button',{name:'Open template',exact:true}).count(),EXPECTED_TEMPLATES);
 await root.getByLabel('Search templates or applications').fill('patient');assert.ok(await root.getByRole('button',{name:'Open template',exact:true}).count()>=3);
 await open('template-patient-master');root=page.locator('[data-template-library="template-patient-master"]');let workspace=root.locator('[data-page-template]');
 await workspace.getByRole('textbox',{name:/^Name/}).fill('Template local edit');await root.getByRole('tab',{name:'TypeScript example',exact:true}).click();const source=root.getByRole('textbox',{name:'TypeScript source / configuration',exact:true});assert.ok((await source.inputValue()).includes('PageTemplateWorkspace'));await root.getByRole('button',{name:'Copy code'}).click();await root.getByText(/Code copied\.|Clipboard unavailable\./).waitFor();await root.getByRole('tab',{name:'Preview',exact:true}).click();assert.equal(await workspace.getByRole('textbox',{name:/^Name/}).inputValue(),'Template local edit');
 await root.getByLabel('Preview layout').selectOption('wizard');assert.equal(await workspace.getByRole('textbox',{name:/^Name/}).inputValue(),'Template local edit');await root.getByLabel('Preview state').selectOption('failure');await workspace.getByRole('button',{name:'Save changes',exact:true}).click();await workspace.getByRole('alert').waitFor();await root.getByLabel('Preview state').selectOption('ready');await workspace.getByRole('button',{name:'Retry',exact:true}).click();await workspace.getByText('Changes saved.',{exact:true}).waitFor();
 assert.deepEqual((await audit(page,{include:'[data-template-library="template-patient-master"]'})).filter(v=>['critical','serious'].includes(v.impact)),[]);await page.screenshot({path:'/tmp/page-template-patient.png'});
 await open('template-purchase-order');root=page.locator('[data-template-library="template-purchase-order"]');workspace=root.locator('[data-page-template]');const count=await workspace.locator('tbody tr').count();await workspace.getByRole('button',{name:'Add line',exact:true}).click();assert.equal(await workspace.locator('tbody tr').count(),count+1);await workspace.getByRole('button',{name:'Remove',exact:true}).last().click();await page.screenshot({path:'/tmp/page-template-order.png'});
 await open('template-appointment');root=page.locator('[data-template-library="template-appointment"]');workspace=root.locator('[data-page-template]');await workspace.locator('[data-template-time="10:00"]').click();assert.equal(await workspace.getByLabel('Start time',{exact:false}).inputValue(),'10:00');await page.screenshot({path:'/tmp/page-template-booking.png'});
 for(const id of ['template-operational-worklist','template-patient-encounter','template-lab-result','template-journal-voucher','template-bank-reconciliation','template-operational-dashboard','template-entity-360','template-permissions-matrix','template-import-wizard']){await open(id);assert.ok(await page.locator(`[data-page-template="${id}"]`).count());}
 root=page.locator('[data-template-library="template-import-wizard"]');await root.locator('input[type=file]').setInputFiles({name:'example.csv',mimeType:'text/csv',buffer:Buffer.from('Code,Name\nEX-1,Example')});await root.getByRole('combobox',{name:'Code',exact:true}).selectOption('0');await root.getByRole('combobox',{name:'Name',exact:true}).selectOption('1');await root.getByRole('button',{name:'Validate rows',exact:true}).click();await root.getByRole('button',{name:'Confirm local import',exact:true}).click();await root.getByText('Rows added to this preview. No API import was performed.',{exact:true}).waitFor();
 for(const language of ['ar','hi','ml','en']){
  await page.keyboard.press('Control+k');let dialog=page.getByRole('dialog');await dialog.locator('input').first().fill('My Preferences');await dialog.locator('button.group').first().click();
  await page.getByRole('tab').filter({hasText:/Language & help|اللغة والمساعدة|भाषा और सहायता|ഭാഷയും സഹായവും/}).click();await page.locator('[data-tour="prefs-lang"] select').selectOption(language);
  await page.waitForFunction(lang=>document.documentElement.lang===lang,language);
  await page.keyboard.press('Control+k');dialog=page.getByRole('dialog');await dialog.locator('input').first().fill('template-patient-master');await dialog.locator('button.group').first().click();
  const catalog=JSON.parse(readFileSync(new URL(`../../dummy-api/config/localization/shared/${language}.json`,import.meta.url),'utf8')).messages;
  const translated=page.locator('[data-page-template="template-patient-master"]');await translated.getByRole('heading',{name:catalog['template.name.patient-master'],exact:true}).waitFor();await translated.getByRole('button',{name:catalog['template.save'],exact:true}).waitFor();
  assert.equal(await page.locator('html').getAttribute('dir'),language==='ar'?'rtl':'ltr');assert.ok(await page.locator('body').evaluate(element=>element.scrollWidth<=innerWidth),'localized page does not overflow horizontally');
 }
 assert.deepEqual(writes,[]);assert.deepEqual(errors,[]);console.log(`PASS ${EXPECTED_TEMPLATES}-template catalog, all engine families, local state across code/layout changes, save recovery, order lines, booking, CSV mapping, four languages/RTL, accessibility, and no business API writes`);
} finally {await browser.close();}
