import {loadPlaywright} from './harness.mjs';
import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync} from 'node:fs';
const {chromium}=loadPlaywright(), browser=await chromium.launch({chromiumSandbox:false});
const artifacts=process.env.E2E_ARTIFACTS??'/tmp/page-list-browser';mkdirSync(artifacts,{recursive:true});
try{
 const p=await browser.newPage({viewport:{width:1700,height:1050}});p.setDefaultTimeout(25000);const errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto(process.env.E2E_DESKTOP??'http://127.0.0.1:3109');await p.locator('input').first().fill('admin');await p.locator('input[type=password]').fill('admin');const navWaiting=p.waitForResponse(r=>new URL(r.url()).pathname.endsWith('/navigation'));await p.keyboard.press('Enter');const nav=await(await navWaiting).json();await p.locator('header').first().waitFor();
 const expected=nav.nodes.filter(n=>n.parentId==='section.library.clinical-templates'&&n.pageId&&n.pageId!=='list-of-pages').sort((a,b)=>a.order-b.order).map(n=>n.pageId);
 async function open(id='list-of-pages'){await p.keyboard.press('Control+k');const d=p.getByRole('dialog');await d.locator('input').first().fill(id);await d.locator('button.group').first().click();}
 await open();const root=p.locator('[data-page-library-catalog]:visible');await root.waitFor();assert.deepEqual(await root.locator('[data-page-library-entry]').evaluateAll(nodes=>nodes.map(n=>n.dataset.pageLibraryEntry)),expected);assert.deepEqual(new Set(expected),new Set(['dcp-designer','emergency-registration','inpatient-admission','consultation-entry-design','consultation-entry-v2','allyvora-patient-query','allyvora-patient-record','allyvora-patient-360','billing-clinic','clinical-triage','clinical-consultation','op-consultation','comprehensive-consultation','op-registration']));
 await root.getByRole('textbox',{name:'Search pages'}).fill('billing-clinic');assert.equal(await root.locator('[data-page-library-entry]').count(),1);await root.getByRole('textbox',{name:'Search pages'}).fill('');
 for(const id of expected){const card=root.locator('[data-page-library-entry="'+id+'"]');await card.getByRole('button',{name:'TypeScript example',exact:true}).click();const dialog=p.getByRole('dialog');const code=await dialog.getByRole('textbox').inputValue();assert.ok(code.includes("from '@pepbits/erp-screens'"));assert.ok(code.includes('scopeKey'));await dialog.getByRole('tab',{name:'User and integration guide',exact:true}).click();assert.ok(!/template\.(clinical|clinic|triage|consultation|op|comprehensive|pageLibrary)\./.test(await dialog.innerText()));await dialog.getByRole('button',{name:'Close',exact:true}).click();}
 await p.screenshot({path:artifacts+'/catalog.png',fullPage:true});
 for(const id of expected){await root.locator('[data-page-library-entry="'+id+'"] button').filter({hasText:'Open page'}).click();await p.locator('header').first().waitFor();const screen=id.startsWith('allyvora')?p.locator('[data-clinical-library="'+id+'"]:visible'):p.locator('[data-'+id+']:visible,[data-care-page="'+id+'"]:visible,[data-tour="'+id+'"]:visible');await screen.waitFor();assert.equal(await p.getByRole('tab',{name:'TypeScript example',exact:true}).count(),0);assert.equal(await p.getByRole('tab',{name:'User and integration guide',exact:true}).count(),0);assert.equal(await screen.getByText('Demo patient search',{exact:true}).count(),0);await p.getByRole('tablist',{name:'Open documents',exact:true}).getByRole('tab',{selected:true}).press('Delete');await open();await root.waitFor();}
 for(const language of ['ar','hi','ml','en']){await open('preferences');await p.getByRole('tab').filter({hasText:/Language & help|اللغة والمساعدة|भाषा और सहायता|ഭാഷയും സഹായവും/}).click();await p.locator('[data-tour="prefs-lang"] select').selectOption(language);await p.waitForFunction(l=>document.documentElement.lang===l,language);await open();await root.waitFor();assert.equal(await root.locator('[data-page-library-entry]').count(),expected.length);assert.ok(!/template\./.test(await root.innerText()));assert.equal(await p.locator('html').getAttribute('dir'),language==='ar'?'rtl':'ltr');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.screenshot({path:artifacts+'/'+language+'.png',fullPage:true});}
 assert.deepEqual(errors,[]);console.log('PASS API navigation list/order, fourteen existing page examples and guides, search, open-page actions, resources removed from working pages, four languages/direction/width, no page errors');
}catch(error){const page=browser.contexts()[0]?.pages()[0];if(page){await page.screenshot({path:artifacts+'/failure.png',fullPage:true});writeFileSync(artifacts+'/failure.json',JSON.stringify({error:error.message,url:page.url(),text:await page.locator('body').innerText()},null,2));}throw error;}finally{await browser.close();}
